unit Unit7;

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils, FileUtil, Forms, Controls, Graphics, Dialogs, StdCtrls,
  ExtCtrls;

type

  { TForm7 }

  TForm7 = class(TForm)
    Button1: TButton;
    GroupBox2: TGroupBox;
    Image1: TImage;
    Image2: TImage;
    Image3: TImage;
    Image4: TImage;
    Image5: TImage;
    Image6: TImage;
    Image7: TImage;
    Image8: TImage;
    RadioButton1: TRadioButton;
    RadioButton2: TRadioButton;
    RadioButton3: TRadioButton;
    RadioButton4: TRadioButton;
    RadioButton5: TRadioButton;
    RadioButton6: TRadioButton;
    RadioButton7: TRadioButton;
    RadioButton8: TRadioButton;
    RadioButton9: TRadioButton;
    procedure Button1Click(Sender: TObject);
    procedure RadioButton10Click(Sender: TObject);
    procedure RadioButton11Click(Sender: TObject);
    procedure RadioButton14Click(Sender: TObject);
    procedure RadioButton15Click(Sender: TObject);
    procedure RadioButton19Click(Sender: TObject);
    procedure RadioButton1Click(Sender: TObject);
    procedure RadioButton2Click(Sender: TObject);
    procedure RadioButton3Click(Sender: TObject);
    procedure RadioButton4Click(Sender: TObject);
    procedure RadioButton5Click(Sender: TObject);
    procedure RadioButton6Click(Sender: TObject);
    procedure RadioButton7Click(Sender: TObject);
    procedure RadioButton8Click(Sender: TObject);
    procedure RadioButton9Click(Sender: TObject);
  private
    { private declarations }
  public
    { public declarations }
  end;

var
  Form7: TForm7;

implementation

uses unit1, unit2, unit3, unit4, unit5, unit6;

{$R *.lfm}

{ TForm7 }

procedure TForm7.Button1Click(Sender: TObject);
begin
  form1.show;
  form7.hide;
end;

procedure TForm7.RadioButton10Click(Sender: TObject);
begin
  attentlang:='ВНИМАНИЕ!!!';
  competlang:='КОНКУРС!!!';
  form1.Label1.caption:='Меню';
  form1.Label3.caption:='Пассивный доход';
  form1.Label4.caption:='Активный доход';
  check:=littlekiosk mod 100;
  case check of
  0: form1.label12.caption:=(inttostr(littlekiosk)+' штук');
  1: form1.label12.caption:=(inttostr(littlekiosk)+' штука');
  2..4: form1.label12.caption:=(inttostr(littlekiosk)+' штуки');
  5..20: form1.label12.caption:=(inttostr(littlekiosk)+' штук');
  21: form1.label12.caption:=(inttostr(littlekiosk)+' штука');
  22..24: form1.label12.caption:=(inttostr(littlekiosk)+' штуки');
  25..30: form1.label12.caption:=(inttostr(littlekiosk)+' штук');
  31: form1.label12.caption:=(inttostr(littlekiosk)+' штука');
  32..34: form1.label12.caption:=(inttostr(littlekiosk)+' штуки');
  35..40: form1.label12.caption:=(inttostr(littlekiosk)+' штук');
  41: form1.label12.caption:=(inttostr(littlekiosk)+' штука');
  42..44: form1.label12.caption:=(inttostr(littlekiosk)+' штуки');
  45..50: form1.label12.caption:=(inttostr(littlekiosk)+' штук');
  51: form1.label12.caption:=(inttostr(littlekiosk)+' штука');
  52..54: form1.label12.caption:=(inttostr(littlekiosk)+' штуки');
  55..60: form1.label12.caption:=(inttostr(littlekiosk)+' штук');
  61: form1.label12.caption:=(inttostr(littlekiosk)+' штука');
  62..64: form1.label12.caption:=(inttostr(littlekiosk)+' штуки');
  65..70: form1.label12.caption:=(inttostr(littlekiosk)+' штук');
  71: form1.label12.caption:=(inttostr(littlekiosk)+' штука');
  72..74: form1.label12.caption:=(inttostr(littlekiosk)+' штуки');
  75..80: form1.label12.caption:=(inttostr(littlekiosk)+' штук');
  81: form1.label12.caption:=(inttostr(littlekiosk)+' штука');
  82..84: form1.label12.caption:=(inttostr(littlekiosk)+' штуки');
  85..90: form1.label12.caption:=(inttostr(littlekiosk)+' штук');
  91: form1.label12.caption:=(inttostr(littlekiosk)+' штука');
  92..94: form1.label12.caption:=(inttostr(littlekiosk)+' штуки');
  95..99: form1.label12.caption:=(inttostr(littlekiosk)+' штук');
  end;
  form1.Label10.caption:='Валюта';
  form1.Label8.caption:='Ваше состояние составляет';
  check:=hoztovari mod 100;
  case check of
  0: form1.label15.caption:=(inttostr(hoztovari)+' штук');
  1: form1.label15.caption:=(inttostr(hoztovari)+' штука');
  2..4: form1.label15.caption:=(inttostr(hoztovari)+' штуки');
  5..20: form1.label15.caption:=(inttostr(hoztovari)+' штук');
  21: form1.label15.caption:=(inttostr(hoztovari)+' штука');
  22..24: form1.label15.caption:=(inttostr(hoztovari)+' штуки');
  25..30: form1.label15.caption:=(inttostr(hoztovari)+' штук');
  31: form1.label15.caption:=(inttostr(hoztovari)+' штука');
  32..34: form1.label15.caption:=(inttostr(hoztovari)+' штуки');
  35..40: form1.label15.caption:=(inttostr(hoztovari)+' штук');
  41: form1.label15.caption:=(inttostr(hoztovari)+' штука');
  42..44: form1.label15.caption:=(inttostr(hoztovari)+' штуки');
  45..50: form1.label15.caption:=(inttostr(hoztovari)+' штук');
  51: form1.label15.caption:=(inttostr(hoztovari)+' штука');
  52..54: form1.label15.caption:=(inttostr(hoztovari)+' штуки');
  55..60: form1.label15.caption:=(inttostr(hoztovari)+' штук');
  61: form1.label15.caption:=(inttostr(hoztovari)+' штука');
  62..64: form1.label15.caption:=(inttostr(hoztovari)+' штуки');
  65..70: form1.label15.caption:=(inttostr(hoztovari)+' штук');
  71: form1.label15.caption:=(inttostr(hoztovari)+' штука');
  72..74: form1.label15.caption:=(inttostr(hoztovari)+' штуки');
  75..80: form1.label15.caption:=(inttostr(hoztovari)+' штук');
  81: form1.label15.caption:=(inttostr(hoztovari)+' штука');
  82..84: form1.label15.caption:=(inttostr(hoztovari)+' штуки');
  85..90: form1.label15.caption:=(inttostr(hoztovari)+' штук');
  91: form1.label15.caption:=(inttostr(hoztovari)+' штука');
  92..94: form1.label15.caption:=(inttostr(hoztovari)+' штуки');
  95..99: form1.label15.caption:=(inttostr(hoztovari)+' штук');
  end;
  check:=gastronom mod 100;
  case check of
  0: form1.label13.caption:=(inttostr(gastronom)+' штук');
  1: form1.label13.caption:=(inttostr(gastronom)+' штука');
  2..4: form1.label13.caption:=(inttostr(gastronom)+' штуки');
  5..20: form1.label13.caption:=(inttostr(gastronom)+' штук');
  21: form1.label13.caption:=(inttostr(gastronom)+' штука');
  22..24: form1.label13.caption:=(inttostr(gastronom)+' штуки');
  25..30: form1.label13.caption:=(inttostr(gastronom)+' штук');
  31: form1.label13.caption:=(inttostr(gastronom)+' штука');
  32..34: form1.label13.caption:=(inttostr(gastronom)+' штуки');
  35..40: form1.label13.caption:=(inttostr(gastronom)+' штук');
  41: form1.label13.caption:=(inttostr(gastronom)+' штука');
  42..44: form1.label13.caption:=(inttostr(gastronom)+' штуки');
  45..50: form1.label13.caption:=(inttostr(gastronom)+' штук');
  51: form1.label13.caption:=(inttostr(gastronom)+' штука');
  52..54: form1.label13.caption:=(inttostr(gastronom)+' штуки');
  55..60: form1.label13.caption:=(inttostr(gastronom)+' штук');
  61: form1.label13.caption:=(inttostr(gastronom)+' штука');
  62..64: form1.label13.caption:=(inttostr(gastronom)+' штуки');
  65..70: form1.label13.caption:=(inttostr(gastronom)+' штук');
  71: form1.label13.caption:=(inttostr(gastronom)+' штука');
  72..74: form1.label13.caption:=(inttostr(gastronom)+' штуки');
  75..80: form1.label13.caption:=(inttostr(gastronom)+' штук');
  81: form1.label13.caption:=(inttostr(gastronom)+' штука');
  82..84: form1.label13.caption:=(inttostr(gastronom)+' штуки');
  85..90: form1.label13.caption:=(inttostr(gastronom)+' штук');
  91: form1.label13.caption:=(inttostr(gastronom)+' штука');
  92..94: form1.label13.caption:=(inttostr(gastronom)+' штуки');
  95..99: form1.label13.caption:=(inttostr(gastronom)+' штук');
  end;
  check:=restaurant mod 100;
  case check of
  0: form1.label14.caption:=(inttostr(restaurant)+' штук');
  1: form1.label14.caption:=(inttostr(restaurant)+' штука');
  2..4: form1.label14.caption:=(inttostr(restaurant)+' штуки');
  5..20: form1.label14.caption:=(inttostr(restaurant)+' штук');
  21: form1.label14.caption:=(inttostr(restaurant)+' штука');
  22..24: form1.label14.caption:=(inttostr(restaurant)+' штуки');
  25..30: form1.label14.caption:=(inttostr(restaurant)+' штук');
  31: form1.label14.caption:=(inttostr(restaurant)+' штука');
  32..34: form1.label14.caption:=(inttostr(restaurant)+' штуки');
  35..40: form1.label14.caption:=(inttostr(restaurant)+' штук');
  41: form1.label14.caption:=(inttostr(restaurant)+' штука');
  42..44: form1.label14.caption:=(inttostr(restaurant)+' штуки');
  45..50: form1.label14.caption:=(inttostr(restaurant)+' штук');
  51: form1.label14.caption:=(inttostr(restaurant)+' штука');
  52..54: form1.label14.caption:=(inttostr(restaurant)+' штуки');
  55..60: form1.label14.caption:=(inttostr(restaurant)+' штук');
  61: form1.label14.caption:=(inttostr(restaurant)+' штука');
  62..64: form1.label14.caption:=(inttostr(restaurant)+' штуки');
  65..70: form1.label14.caption:=(inttostr(restaurant)+' штук');
  71: form1.label14.caption:=(inttostr(restaurant)+' штука');
  72..74: form1.label14.caption:=(inttostr(restaurant)+' штуки');
  75..80: form1.label14.caption:=(inttostr(restaurant)+' штук');
  81: form1.label14.caption:=(inttostr(restaurant)+' штука');
  82..84: form1.label14.caption:=(inttostr(restaurant)+' штуки');
  85..90: form1.label14.caption:=(inttostr(restaurant)+' штук');
  91: form1.label14.caption:=(inttostr(restaurant)+' штука');
  92..94: form1.label14.caption:=(inttostr(restaurant)+' штуки');
  95..99: form1.label14.caption:=(inttostr(restaurant)+' штук');
  end;
  check:=apteka mod 100;
  case check of
  0: form1.label16.caption:=(inttostr(apteka)+' штук');
  1: form1.label16.caption:=(inttostr(apteka)+' штука');
  2..4: form1.label16.caption:=(inttostr(apteka)+' штуки');
  5..20: form1.label16.caption:=(inttostr(apteka)+' штук');
  21: form1.label16.caption:=(inttostr(apteka)+' штука');
  22..24: form1.label16.caption:=(inttostr(apteka)+' штуки');
  25..30: form1.label16.caption:=(inttostr(apteka)+' штук');
  31: form1.label16.caption:=(inttostr(apteka)+' штука');
  32..34: form1.label16.caption:=(inttostr(apteka)+' штуки');
  35..40: form1.label16.caption:=(inttostr(apteka)+' штук');
  41: form1.label16.caption:=(inttostr(apteka)+' штука');
  42..44: form1.label16.caption:=(inttostr(apteka)+' штуки');
  45..50: form1.label16.caption:=(inttostr(apteka)+' штук');
  51: form1.label16.caption:=(inttostr(apteka)+' штука');
  52..54: form1.label16.caption:=(inttostr(apteka)+' штуки');
  55..60: form1.label16.caption:=(inttostr(apteka)+' штук');
  61: form1.label16.caption:=(inttostr(apteka)+' штука');
  62..64: form1.label16.caption:=(inttostr(apteka)+' штуки');
  65..70: form1.label16.caption:=(inttostr(apteka)+' штук');
  71: form1.label16.caption:=(inttostr(apteka)+' штука');
  72..74: form1.label16.caption:=(inttostr(apteka)+' штуки');
  75..80: form1.label16.caption:=(inttostr(apteka)+' штук');
  81: form1.label16.caption:=(inttostr(apteka)+' штука');
  82..84: form1.label16.caption:=(inttostr(apteka)+' штуки');
  85..90: form1.label16.caption:=(inttostr(apteka)+' штук');
  91: form1.label16.caption:=(inttostr(apteka)+' штука');
  92..94: form1.label16.caption:=(inttostr(apteka)+' штуки');
  95..99: form1.label16.caption:=(inttostr(apteka)+' штук');
  end;
  check:=cinema mod 100;
  case check of
  0: form1.label17.caption:=(inttostr(cinema)+' штук');
  1: form1.label17.caption:=(inttostr(cinema)+' штука');
  2..4: form1.label17.caption:=(inttostr(cinema)+' штуки');
  5..20: form1.label17.caption:=(inttostr(cinema)+' штук');
  21: form1.label17.caption:=(inttostr(cinema)+' штука');
  22..24: form1.label17.caption:=(inttostr(cinema)+' штуки');
  25..30: form1.label17.caption:=(inttostr(cinema)+' штук');
  31: form1.label17.caption:=(inttostr(cinema)+' штука');
  32..34: form1.label17.caption:=(inttostr(cinema)+' штуки');
  35..40: form1.label17.caption:=(inttostr(cinema)+' штук');
  41: form1.label17.caption:=(inttostr(cinema)+' штука');
  42..44: form1.label17.caption:=(inttostr(cinema)+' штуки');
  45..50: form1.label17.caption:=(inttostr(cinema)+' штук');
  51: form1.label17.caption:=(inttostr(cinema)+' штука');
  52..54: form1.label17.caption:=(inttostr(cinema)+' штуки');
  55..60: form1.label17.caption:=(inttostr(cinema)+' штук');
  61: form1.label17.caption:=(inttostr(cinema)+' штука');
  62..64: form1.label17.caption:=(inttostr(cinema)+' штуки');
  65..70: form1.label17.caption:=(inttostr(cinema)+' штук');
  71: form1.label17.caption:=(inttostr(cinema)+' штука');
  72..74: form1.label17.caption:=(inttostr(cinema)+' штуки');
  75..80: form1.label17.caption:=(inttostr(cinema)+' штук');
  81: form1.label17.caption:=(inttostr(cinema)+' штука');
  82..84: form1.label17.caption:=(inttostr(cinema)+' штуки');
  85..90: form1.label17.caption:=(inttostr(cinema)+' штук');
  91: form1.label17.caption:=(inttostr(cinema)+' штука');
  92..94: form1.label17.caption:=(inttostr(cinema)+' штуки');
  95..99: form1.label17.caption:=(inttostr(cinema)+' штук');
  end;
  check:=cinemastudio mod 100;
  case check of
  0: form1.label18.caption:=(inttostr(cinemastudio)+' штук');
  1: form1.label18.caption:=(inttostr(cinemastudio)+' штука');
  2..4: form1.label18.caption:=(inttostr(cinemastudio)+' штуки');
  5..20: form1.label18.caption:=(inttostr(cinemastudio)+' штук');
  21: form1.label18.caption:=(inttostr(cinemastudio)+' штука');
  22..24: form1.label18.caption:=(inttostr(cinemastudio)+' штуки');
  25..30: form1.label18.caption:=(inttostr(cinemastudio)+' штук');
  31: form1.label18.caption:=(inttostr(cinemastudio)+' штука');
  32..34: form1.label18.caption:=(inttostr(cinemastudio)+' штуки');
  35..40: form1.label18.caption:=(inttostr(cinemastudio)+' штук');
  41: form1.label18.caption:=(inttostr(cinemastudio)+' штука');
  42..44: form1.label18.caption:=(inttostr(cinemastudio)+' штуки');
  45..50: form1.label18.caption:=(inttostr(cinemastudio)+' штук');
  51: form1.label18.caption:=(inttostr(cinemastudio)+' штука');
  52..54: form1.label18.caption:=(inttostr(cinemastudio)+' штуки');
  55..60: form1.label18.caption:=(inttostr(cinemastudio)+' штук');
  61: form1.label18.caption:=(inttostr(cinemastudio)+' штука');
  62..64: form1.label18.caption:=(inttostr(cinemastudio)+' штуки');
  65..70: form1.label18.caption:=(inttostr(cinemastudio)+' штук');
  71: form1.label18.caption:=(inttostr(cinemastudio)+' штука');
  72..74: form1.label18.caption:=(inttostr(cinemastudio)+' штуки');
  75..80: form1.label18.caption:=(inttostr(cinemastudio)+' штук');
  81: form1.label18.caption:=(inttostr(cinemastudio)+' штука');
  82..84: form1.label18.caption:=(inttostr(cinemastudio)+' штуки');
  85..90: form1.label18.caption:=(inttostr(cinemastudio)+' штук');
  91: form1.label18.caption:=(inttostr(cinemastudio)+' штука');
  92..94: form1.label18.caption:=(inttostr(cinemastudio)+' штуки');
  95..99: form1.label18.caption:=(inttostr(cinemastudio)+' штук');
  end;
  check:=hostel mod 100;
  case check of
  0: form1.label19.caption:=(inttostr(hostel)+' штук');
  1: form1.label19.caption:=(inttostr(hostel)+' штука');
  2..4: form1.label19.caption:=(inttostr(hostel)+' штуки');
  5..20: form1.label19.caption:=(inttostr(hostel)+' штук');
  21: form1.label19.caption:=(inttostr(hostel)+' штука');
  22..24: form1.label19.caption:=(inttostr(hostel)+' штуки');
  25..30: form1.label19.caption:=(inttostr(hostel)+' штук');
  31: form1.label19.caption:=(inttostr(hostel)+' штука');
  32..34: form1.label19.caption:=(inttostr(hostel)+' штуки');
  35..40: form1.label19.caption:=(inttostr(hostel)+' штук');
  41: form1.label19.caption:=(inttostr(hostel)+' штука');
  42..44: form1.label19.caption:=(inttostr(hostel)+' штуки');
  45..50: form1.label19.caption:=(inttostr(hostel)+' штук');
  51: form1.label19.caption:=(inttostr(hostel)+' штука');
  52..54: form1.label19.caption:=(inttostr(hostel)+' штуки');
  55..60: form1.label19.caption:=(inttostr(hostel)+' штук');
  61: form1.label19.caption:=(inttostr(hostel)+' штука');
  62..64: form1.label19.caption:=(inttostr(hostel)+' штуки');
  65..70: form1.label19.caption:=(inttostr(hostel)+' штук');
  71: form1.label19.caption:=(inttostr(hostel)+' штука');
  72..74: form1.label19.caption:=(inttostr(hostel)+' штуки');
  75..80: form1.label19.caption:=(inttostr(hostel)+' штук');
  81: form1.label19.caption:=(inttostr(hostel)+' штука');
  82..84: form1.label19.caption:=(inttostr(hostel)+' штуки');
  85..90: form1.label19.caption:=(inttostr(hostel)+' штук');
  91: form1.label19.caption:=(inttostr(hostel)+' штука');
  92..94: form1.label19.caption:=(inttostr(hostel)+' штуки');
  95..99: form1.label19.caption:=(inttostr(hostel)+' штук');
  end;
  check:=hotel mod 100;
  case check of
  0: form1.label20.caption:=(inttostr(hotel)+' штук');
  1: form1.label20.caption:=(inttostr(hotel)+' штука');
  2..4: form1.label20.caption:=(inttostr(hotel)+' штуки');
  5..20: form1.label20.caption:=(inttostr(hotel)+' штук');
  21: form1.label20.caption:=(inttostr(hotel)+' штука');
  22..24: form1.label20.caption:=(inttostr(hotel)+' штуки');
  25..30: form1.label20.caption:=(inttostr(hotel)+' штук');
  31: form1.label20.caption:=(inttostr(hotel)+' штука');
  32..34: form1.label20.caption:=(inttostr(hotel)+' штуки');
  35..40: form1.label20.caption:=(inttostr(hotel)+' штук');
  41: form1.label20.caption:=(inttostr(hotel)+' штука');
  42..44: form1.label20.caption:=(inttostr(hotel)+' штуки');
  45..50: form1.label20.caption:=(inttostr(hotel)+' штук');
  51: form1.label20.caption:=(inttostr(hotel)+' штука');
  52..54: form1.label20.caption:=(inttostr(hotel)+' штуки');
  55..60: form1.label20.caption:=(inttostr(hotel)+' штук');
  61: form1.label20.caption:=(inttostr(hotel)+' штука');
  62..64: form1.label20.caption:=(inttostr(hotel)+' штуки');
  65..70: form1.label20.caption:=(inttostr(hotel)+' штук');
  71: form1.label20.caption:=(inttostr(hotel)+' штука');
  72..74: form1.label20.caption:=(inttostr(hotel)+' штуки');
  75..80: form1.label20.caption:=(inttostr(hotel)+' штук');
  81: form1.label20.caption:=(inttostr(hotel)+' штука');
  82..84: form1.label20.caption:=(inttostr(hotel)+' штуки');
  85..90: form1.label20.caption:=(inttostr(hotel)+' штук');
  91: form1.label20.caption:=(inttostr(hotel)+' штука');
  92..94: form1.label20.caption:=(inttostr(hotel)+' штуки');
  95..99: form1.label20.caption:=(inttostr(hotel)+' штук');
  end;
  check:=TC mod 100;
  case check of
  0: form1.label21.caption:=(inttostr(TC)+' штук');
  1: form1.label21.caption:=(inttostr(TC)+' штука');
  2..4: form1.label21.caption:=(inttostr(TC)+' штуки');
  5..20: form1.label21.caption:=(inttostr(TC)+' штук');
  21: form1.label21.caption:=(inttostr(TC)+' штука');
  22..24: form1.label21.caption:=(inttostr(TC)+' штуки');
  25..30: form1.label21.caption:=(inttostr(TC)+' штук');
  31: form1.label21.caption:=(inttostr(TC)+' штука');
  32..34: form1.label21.caption:=(inttostr(TC)+' штуки');
  35..40: form1.label21.caption:=(inttostr(TC)+' штук');
  41: form1.label21.caption:=(inttostr(TC)+' штука');
  42..44: form1.label21.caption:=(inttostr(TC)+' штуки');
  45..50: form1.label21.caption:=(inttostr(TC)+' штук');
  51: form1.label21.caption:=(inttostr(TC)+' штука');
  52..54: form1.label21.caption:=(inttostr(TC)+' штуки');
  55..60: form1.label21.caption:=(inttostr(TC)+' штук');
  61: form1.label21.caption:=(inttostr(TC)+' штука');
  62..64: form1.label21.caption:=(inttostr(TC)+' штуки');
  65..70: form1.label21.caption:=(inttostr(TC)+' штук');
  71: form1.label21.caption:=(inttostr(TC)+' штука');
  72..74: form1.label21.caption:=(inttostr(TC)+' штуки');
  75..80: form1.label21.caption:=(inttostr(TC)+' штук');
  81: form1.label21.caption:=(inttostr(TC)+' штука');
  82..84: form1.label21.caption:=(inttostr(TC)+' штуки');
  85..90: form1.label21.caption:=(inttostr(TC)+' штук');
  91: form1.label21.caption:=(inttostr(TC)+' штука');
  92..94: form1.label21.caption:=(inttostr(TC)+' штуки');
  95..99: form1.label21.caption:=(inttostr(TC)+' штук');
  end;
  check:=autoservice mod 100;
  case check of
  0: form1.label22.caption:=(inttostr(autoservice)+' штук');
  1: form1.label22.caption:=(inttostr(autoservice)+' штука');
  2..4: form1.label22.caption:=(inttostr(autoservice)+' штуки');
  5..20: form1.label22.caption:=(inttostr(autoservice)+' штук');
  21: form1.label22.caption:=(inttostr(autoservice)+' штука');
  22..24: form1.label22.caption:=(inttostr(autoservice)+' штуки');
  25..30: form1.label22.caption:=(inttostr(autoservice)+' штук');
  31: form1.label22.caption:=(inttostr(autoservice)+' штука');
  32..34: form1.label22.caption:=(inttostr(autoservice)+' штуки');
  35..40: form1.label22.caption:=(inttostr(autoservice)+' штук');
  41: form1.label22.caption:=(inttostr(autoservice)+' штука');
  42..44: form1.label22.caption:=(inttostr(autoservice)+' штуки');
  45..50: form1.label22.caption:=(inttostr(autoservice)+' штук');
  51: form1.label22.caption:=(inttostr(autoservice)+' штука');
  52..54: form1.label22.caption:=(inttostr(autoservice)+' штуки');
  55..60: form1.label22.caption:=(inttostr(autoservice)+' штук');
  61: form1.label22.caption:=(inttostr(autoservice)+' штука');
  62..64: form1.label22.caption:=(inttostr(autoservice)+' штуки');
  65..70: form1.label22.caption:=(inttostr(autoservice)+' штук');
  71: form1.label22.caption:=(inttostr(autoservice)+' штука');
  72..74: form1.label22.caption:=(inttostr(autoservice)+' штуки');
  75..80: form1.label22.caption:=(inttostr(autoservice)+' штук');
  81: form1.label22.caption:=(inttostr(autoservice)+' штука');
  82..84: form1.label22.caption:=(inttostr(autoservice)+' штуки');
  85..90: form1.label22.caption:=(inttostr(autoservice)+' штук');
  91: form1.label22.caption:=(inttostr(autoservice)+' штука');
  92..94: form1.label22.caption:=(inttostr(autoservice)+' штуки');
  95..99: form1.label22.caption:=(inttostr(autoservice)+' штук');
  end;
  check:=fitness mod 100;
  case check of
  0: form1.label23.caption:=(inttostr(fitness)+' штук');
  1: form1.label23.caption:=(inttostr(fitness)+' штука');
  2..4: form1.label23.caption:=(inttostr(fitness)+' штуки');
  5..20: form1.label23.caption:=(inttostr(fitness)+' штук');
  21: form1.label23.caption:=(inttostr(fitness)+' штука');
  22..24: form1.label23.caption:=(inttostr(fitness)+' штуки');
  25..30: form1.label23.caption:=(inttostr(fitness)+' штук');
  31: form1.label23.caption:=(inttostr(fitness)+' штука');
  32..34: form1.label23.caption:=(inttostr(fitness)+' штуки');
  35..40: form1.label23.caption:=(inttostr(fitness)+' штук');
  41: form1.label23.caption:=(inttostr(fitness)+' штука');
  42..44: form1.label23.caption:=(inttostr(fitness)+' штуки');
  45..50: form1.label23.caption:=(inttostr(fitness)+' штук');
  51: form1.label23.caption:=(inttostr(fitness)+' штука');
  52..54: form1.label23.caption:=(inttostr(fitness)+' штуки');
  55..60: form1.label23.caption:=(inttostr(fitness)+' штук');
  61: form1.label23.caption:=(inttostr(fitness)+' штука');
  62..64: form1.label23.caption:=(inttostr(fitness)+' штуки');
  65..70: form1.label23.caption:=(inttostr(fitness)+' штук');
  71: form1.label23.caption:=(inttostr(fitness)+' штука');
  72..74: form1.label23.caption:=(inttostr(fitness)+' штуки');
  75..80: form1.label23.caption:=(inttostr(fitness)+' штук');
  81: form1.label23.caption:=(inttostr(fitness)+' штука');
  82..84: form1.label23.caption:=(inttostr(fitness)+' штуки');
  85..90: form1.label23.caption:=(inttostr(fitness)+' штук');
  91: form1.label23.caption:=(inttostr(fitness)+' штука');
  92..94: form1.label23.caption:=(inttostr(fitness)+' штуки');
  95..99: form1.label23.caption:=(inttostr(fitness)+' штук');
  end;
  check:=beauty mod 100;
  case check of
  0: form1.label24.caption:=(inttostr(beauty)+' штук');
  1: form1.label24.caption:=(inttostr(beauty)+' штука');
  2..4: form1.label24.caption:=(inttostr(beauty)+' штуки');
  5..20: form1.label24.caption:=(inttostr(beauty)+' штук');
  21: form1.label24.caption:=(inttostr(beauty)+' штука');
  22..24: form1.label24.caption:=(inttostr(beauty)+' штуки');
  25..30: form1.label24.caption:=(inttostr(beauty)+' штук');
  31: form1.label24.caption:=(inttostr(beauty)+' штука');
  32..34: form1.label24.caption:=(inttostr(beauty)+' штуки');
  35..40: form1.label24.caption:=(inttostr(beauty)+' штук');
  41: form1.label24.caption:=(inttostr(beauty)+' штука');
  42..44: form1.label24.caption:=(inttostr(beauty)+' штуки');
  45..50: form1.label24.caption:=(inttostr(beauty)+' штук');
  51: form1.label24.caption:=(inttostr(beauty)+' штука');
  52..54: form1.label24.caption:=(inttostr(beauty)+' штуки');
  55..60: form1.label24.caption:=(inttostr(beauty)+' штук');
  61: form1.label24.caption:=(inttostr(beauty)+' штука');
  62..64: form1.label24.caption:=(inttostr(beauty)+' штуки');
  65..70: form1.label24.caption:=(inttostr(beauty)+' штук');
  71: form1.label24.caption:=(inttostr(beauty)+' штука');
  72..74: form1.label24.caption:=(inttostr(beauty)+' штуки');
  75..80: form1.label24.caption:=(inttostr(beauty)+' штук');
  81: form1.label24.caption:=(inttostr(beauty)+' штука');
  82..84: form1.label24.caption:=(inttostr(beauty)+' штуки');
  85..90: form1.label24.caption:=(inttostr(beauty)+' штук');
  91: form1.label24.caption:=(inttostr(beauty)+' штука');
  92..94: form1.label24.caption:=(inttostr(beauty)+' штуки');
  95..99: form1.label24.caption:=(inttostr(beauty)+' штук');
  end;
  check:=stomatologia mod 100;
  case check of
  0: form1.label25.caption:=(inttostr(stomatologia)+' штук');
  1: form1.label25.caption:=(inttostr(stomatologia)+' штука');
  2..4: form1.label25.caption:=(inttostr(stomatologia)+' штуки');
  5..20: form1.label25.caption:=(inttostr(stomatologia)+' штук');
  21: form1.label25.caption:=(inttostr(stomatologia)+' штука');
  22..24: form1.label25.caption:=(inttostr(stomatologia)+' штуки');
  25..30: form1.label25.caption:=(inttostr(stomatologia)+' штук');
  31: form1.label25.caption:=(inttostr(stomatologia)+' штука');
  32..34: form1.label25.caption:=(inttostr(stomatologia)+' штуки');
  35..40: form1.label25.caption:=(inttostr(stomatologia)+' штук');
  41: form1.label25.caption:=(inttostr(stomatologia)+' штука');
  42..44: form1.label25.caption:=(inttostr(stomatologia)+' штуки');
  45..50: form1.label25.caption:=(inttostr(stomatologia)+' штук');
  51: form1.label25.caption:=(inttostr(stomatologia)+' штука');
  52..54: form1.label25.caption:=(inttostr(stomatologia)+' штуки');
  55..60: form1.label25.caption:=(inttostr(stomatologia)+' штук');
  61: form1.label25.caption:=(inttostr(stomatologia)+' штука');
  62..64: form1.label25.caption:=(inttostr(stomatologia)+' штуки');
  65..70: form1.label25.caption:=(inttostr(stomatologia)+' штук');
  71: form1.label25.caption:=(inttostr(stomatologia)+' штука');
  72..74: form1.label25.caption:=(inttostr(stomatologia)+' штуки');
  75..80: form1.label25.caption:=(inttostr(stomatologia)+' штук');
  81: form1.label25.caption:=(inttostr(stomatologia)+' штука');
  82..84: form1.label25.caption:=(inttostr(stomatologia)+' штуки');
  85..90: form1.label25.caption:=(inttostr(stomatologia)+' штук');
  91: form1.label25.caption:=(inttostr(stomatologia)+' штука');
  92..94: form1.label25.caption:=(inttostr(stomatologia)+' штуки');
  95..99: form1.label25.caption:=(inttostr(stomatologia)+' штук');
  end;
  check:=socnet mod 100;
  case check of
  0: form1.label26.caption:=(inttostr(socnet)+' штук');
  1: form1.label26.caption:=(inttostr(socnet)+' штука');
  2..4: form1.label26.caption:=(inttostr(socnet)+' штуки');
  5..20: form1.label26.caption:=(inttostr(socnet)+' штук');
  21: form1.label26.caption:=(inttostr(socnet)+' штука');
  22..24: form1.label26.caption:=(inttostr(socnet)+' штуки');
  25..30: form1.label26.caption:=(inttostr(socnet)+' штук');
  31: form1.label26.caption:=(inttostr(socnet)+' штука');
  32..34: form1.label26.caption:=(inttostr(socnet)+' штуки');
  35..40: form1.label26.caption:=(inttostr(socnet)+' штук');
  41: form1.label26.caption:=(inttostr(socnet)+' штука');
  42..44: form1.label26.caption:=(inttostr(socnet)+' штуки');
  45..50: form1.label26.caption:=(inttostr(socnet)+' штук');
  51: form1.label26.caption:=(inttostr(socnet)+' штука');
  52..54: form1.label26.caption:=(inttostr(socnet)+' штуки');
  55..60: form1.label26.caption:=(inttostr(socnet)+' штук');
  61: form1.label26.caption:=(inttostr(socnet)+' штука');
  62..64: form1.label26.caption:=(inttostr(socnet)+' штуки');
  65..70: form1.label26.caption:=(inttostr(socnet)+' штук');
  71: form1.label26.caption:=(inttostr(socnet)+' штука');
  72..74: form1.label26.caption:=(inttostr(socnet)+' штуки');
  75..80: form1.label26.caption:=(inttostr(socnet)+' штук');
  81: form1.label26.caption:=(inttostr(socnet)+' штука');
  82..84: form1.label26.caption:=(inttostr(socnet)+' штуки');
  85..90: form1.label26.caption:=(inttostr(socnet)+' штук');
  91: form1.label26.caption:=(inttostr(socnet)+' штука');
  92..94: form1.label26.caption:=(inttostr(socnet)+' штуки');
  95..99: form1.label26.caption:=(inttostr(socnet)+' штук');
  end;
  check:=bank mod 100;
  case check of
  0: form1.label27.caption:=(inttostr(bank)+' штук');
  1: form1.label27.caption:=(inttostr(bank)+' штука');
  2..4: form1.label27.caption:=(inttostr(bank)+' штуки');
  5..20: form1.label27.caption:=(inttostr(bank)+' штук');
  21: form1.label27.caption:=(inttostr(bank)+' штука');
  22..24: form1.label27.caption:=(inttostr(bank)+' штуки');
  25..30: form1.label27.caption:=(inttostr(bank)+' штук');
  31: form1.label27.caption:=(inttostr(bank)+' штука');
  32..34: form1.label27.caption:=(inttostr(bank)+' штуки');
  35..40: form1.label27.caption:=(inttostr(bank)+' штук');
  41: form1.label27.caption:=(inttostr(bank)+' штука');
  42..44: form1.label27.caption:=(inttostr(bank)+' штуки');
  45..50: form1.label27.caption:=(inttostr(bank)+' штук');
  51: form1.label27.caption:=(inttostr(bank)+' штука');
  52..54: form1.label27.caption:=(inttostr(bank)+' штуки');
  55..60: form1.label27.caption:=(inttostr(bank)+' штук');
  61: form1.label27.caption:=(inttostr(bank)+' штука');
  62..64: form1.label27.caption:=(inttostr(bank)+' штуки');
  65..70: form1.label27.caption:=(inttostr(bank)+' штук');
  71: form1.label27.caption:=(inttostr(bank)+' штука');
  72..74: form1.label27.caption:=(inttostr(bank)+' штуки');
  75..80: form1.label27.caption:=(inttostr(bank)+' штук');
  81: form1.label27.caption:=(inttostr(bank)+' штука');
  82..84: form1.label27.caption:=(inttostr(bank)+' штуки');
  85..90: form1.label27.caption:=(inttostr(bank)+' штук');
  91: form1.label27.caption:=(inttostr(bank)+' штука');
  92..94: form1.label27.caption:=(inttostr(bank)+' штуки');
  95..99: form1.label27.caption:=(inttostr(bank)+' штук');
  end;
  check:=blackgold mod 100;
  case check of
  0: form1.label28.caption:=(inttostr(blackgold)+' штук');
  1: form1.label28.caption:=(inttostr(blackgold)+' штука');
  2..4: form1.label28.caption:=(inttostr(blackgold)+' штуки');
  5..20: form1.label28.caption:=(inttostr(blackgold)+' штук');
  21: form1.label28.caption:=(inttostr(blackgold)+' штука');
  22..24: form1.label28.caption:=(inttostr(blackgold)+' штуки');
  25..30: form1.label28.caption:=(inttostr(blackgold)+' штук');
  31: form1.label28.caption:=(inttostr(blackgold)+' штука');
  32..34: form1.label28.caption:=(inttostr(blackgold)+' штуки');
  35..40: form1.label28.caption:=(inttostr(blackgold)+' штук');
  41: form1.label28.caption:=(inttostr(blackgold)+' штука');
  42..44: form1.label28.caption:=(inttostr(blackgold)+' штуки');
  45..50: form1.label28.caption:=(inttostr(blackgold)+' штук');
  51: form1.label28.caption:=(inttostr(blackgold)+' штука');
  52..54: form1.label28.caption:=(inttostr(blackgold)+' штуки');
  55..60: form1.label28.caption:=(inttostr(blackgold)+' штук');
  61: form1.label28.caption:=(inttostr(blackgold)+' штука');
  62..64: form1.label28.caption:=(inttostr(blackgold)+' штуки');
  65..70: form1.label28.caption:=(inttostr(blackgold)+' штук');
  71: form1.label28.caption:=(inttostr(blackgold)+' штука');
  72..74: form1.label28.caption:=(inttostr(blackgold)+' штуки');
  75..80: form1.label28.caption:=(inttostr(blackgold)+' штук');
  81: form1.label28.caption:=(inttostr(blackgold)+' штука');
  82..84: form1.label28.caption:=(inttostr(blackgold)+' штуки');
  85..90: form1.label28.caption:=(inttostr(blackgold)+' штук');
  91: form1.label28.caption:=(inttostr(blackgold)+' штука');
  92..94: form1.label28.caption:=(inttostr(blackgold)+' штуки');
  95..99: form1.label28.caption:=(inttostr(blackgold)+' штук');
  end;
  check:=va mod 100;
  case check of
  0: form1.label12.caption:=(inttostr(va)+' штук');
  1: form1.label12.caption:=(inttostr(va)+' штука');
  2..4: form1.label12.caption:=(inttostr(va)+' штуки');
  5..20: form1.label12.caption:=(inttostr(va)+' штук');
  21: form1.label12.caption:=(inttostr(va)+' штука');
  22..24: form1.label12.caption:=(inttostr(va)+' штуки');
  25..30: form1.label12.caption:=(inttostr(va)+' штук');
  31: form1.label12.caption:=(inttostr(va)+' штука');
  32..34: form1.label12.caption:=(inttostr(va)+' штуки');
  35..40: form1.label12.caption:=(inttostr(va)+' штук');
  41: form1.label12.caption:=(inttostr(va)+' штука');
  42..44: form1.label12.caption:=(inttostr(va)+' штуки');
  45..50: form1.label12.caption:=(inttostr(va)+' штук');
  51: form1.label12.caption:=(inttostr(va)+' штука');
  52..54: form1.label12.caption:=(inttostr(va)+' штуки');
  55..60: form1.label12.caption:=(inttostr(va)+' штук');
  61: form1.label12.caption:=(inttostr(va)+' штука');
  62..64: form1.label12.caption:=(inttostr(va)+' штуки');
  65..70: form1.label12.caption:=(inttostr(va)+' штук');
  71: form1.label12.caption:=(inttostr(va)+' штука');
  72..74: form1.label12.caption:=(inttostr(va)+' штуки');
  75..80: form1.label12.caption:=(inttostr(va)+' штук');
  81: form1.label12.caption:=(inttostr(va)+' штука');
  82..84: form1.label12.caption:=(inttostr(va)+' штуки');
  85..90: form1.label12.caption:=(inttostr(va)+' штук');
  91: form1.label12.caption:=(inttostr(va)+' штука');
  92..94: form1.label12.caption:=(inttostr(va)+' штуки');
  95..99: form1.label12.caption:=(inttostr(va)+' штук');
  end;
  form1.Label66.caption:='Ваш уровень акт. дохода';
  form1.Label65.caption:='Ваш уровень пасс. дохода';
  form1.Label2.caption:='Ваш уровень опыта';
  form1.statictext1.caption:='Симулятор бизнесмена';
  form1.statictext8.caption:='Маленький киоск';
  form1.statictext9.caption:='Хозтовары';
  form1.statictext10.caption:='Гастроном';
  form1.statictext19.caption:='Ресторан';
  form1.statictext11.caption:='Аптека';
  form1.statictext12.caption:='Кинотеатр';
  form1.statictext24.caption:='Студия геймдева';
  form1.statictext13.caption:='Хостел';
  form1.statictext14.caption:='Отель';
  form1.statictext15.caption:='Торговый центр';
  form1.statictext17.caption:='Автосервис';
  form1.statictext16.caption:='Фитнес-центр';
  form1.statictext18.caption:='Салон красоты';
  form1.statictext20.caption:='Стоматология';
  form1.statictext23.caption:='Социальная сеть';
  form1.statictext21.caption:='Банк';
  form1.statictext22.caption:='Нефтекомпания';
  form1.statictext25.caption:='Ваша активность';
  form1.statictext43.caption:='Ваша стоимость';
  form1.button2.caption:='Сохранить';
  form1.button3.caption:='Загрузить';
  form1.button4.caption:='Выход';
  form1.button5.caption:='Авторы';
  form1.button1.caption:='Справка';
  form1.button7.caption:='Статистика';
  form1.button9.caption:='Пожертвовать';
  form1.button10.caption:='Ачивки';
  form1.button11.caption:='БагРепорт';
  form1.button31.caption:='Настройки';
  form1.button13.caption:='Купить';
  form1.button14.caption:='Купить';
  form1.button15.caption:='Купить';
  form1.button16.caption:='Купить';
  form1.button17.caption:='Купить';
  form1.button18.caption:='Купить';
  form1.button19.caption:='Купить';
  form1.button20.caption:='Купить';
  form1.button21.caption:='Купить';
  form1.button22.caption:='Купить';
  form1.button23.caption:='Купить';
  form1.button24.caption:='Купить';
  form1.button25.caption:='Купить';
  form1.button26.caption:='Купить';
  form1.button27.caption:='Купить';
  form1.button28.caption:='Купить';
  form1.button29.caption:='Купить';
  form1.button30.caption:='Купить';
  form1.button8.caption:='Лотерея';
  form1.button6.caption:='Работать';
  form1.radiobutton1.caption:='Рубли';
  form1.radiobutton2.caption:='Доллары';
  form1.radiobutton3.caption:='Евро';
  form1.radiobutton4.caption:='Юани';
  form1.radiobutton5.caption:='Фунты Стерл.';
  form2.button1.caption:='Назад';
  form2.tabsheet1.caption:='Пассивный доход';
  form2.tabsheet2.caption:='Активный доход';
  form2.tabsheet3.caption:='Деньги на руках';
  form2.tabsheet4.caption:='Маленький киоск';
  form2.tabsheet5.caption:='Хозтовары';
  form2.tabsheet6.caption:='Гастроном';
  form2.tabsheet7.caption:='Ресторан';
  form2.tabsheet8.caption:='Аптека';
  form2.tabsheet9.caption:='Кинотеатр';
  form2.tabsheet10.caption:='Студия геймдева';
  form2.tabsheet11.caption:='Хостел';
  form2.tabsheet12.caption:='Отель';
  form2.tabsheet13.caption:='Торговый центр';
  form2.tabsheet14.caption:='Автосервис';
  form2.tabsheet15.caption:='Фитнес-центр';
  form2.tabsheet16.caption:='Салон красоты';
  form2.tabsheet17.caption:='Стоматология';
  form2.tabsheet18.caption:='Социальная сеть';
  form2.tabsheet19.caption:='Банк';
  form2.tabsheet20.caption:='Нефтекомпания';
  form2.tabsheet21.caption:='Ваша активность';
  form2.tabsheet24.caption:='Все активности';
  form2.tabsheet23.caption:='Другое';
  form3.statictext1.caption:='Нравится игра? Оставить отзыв на сайте?';
  form3.button1.caption:='Да';
  form3.button2.caption:='Больше не напоминать';
  form3.button3.caption:='Не сейчас';
  form4.button1.caption:='Закрыть через 15 секунд';
  form5.button1.caption:='Применить';
  form5.label1.caption:='Введите секретный ключ';
  form6.label1.caption:='Каким браузером ты пользуешься?';
  form6.button4.caption:='Другой';
  form7.groupbox2.caption:='Фон';
  form7.radiobutton9.caption:='Без фона';
  form7.button1.caption:='Назад в игру';
  form1.caption:='Симулятор бизнесмена';
  form2.caption:='Ачивки';
  form3.caption:='Симулятор бизнесмена';
  form4.caption:='Реклама';
  form7.caption:='Настройки';
  language:='russian';
  check:=0;
end;

procedure TForm7.RadioButton11Click(Sender: TObject);
begin
  attentlang:='ATTENTION';
  competlang:='COMPETITION';
  form1.Label1.caption:='Menu';
  form1.Label3.caption:='Passive profit';
  form1.Label4.caption:='Active profit';
  if littlekiosk<>1 then
  form1.Label12.caption:=inttostr(littlekiosk)+' pieces' else
  form1.Label12.caption:=inttostr(littlekiosk)+' piece';
  form1.Label10.caption:='Currency';
  form1.Label8.caption:='Money that you have:';
  if hoztovari<>1 then
  form1.Label15.caption:=inttostr(hoztovari)+' pieces' else
  form1.Label15.caption:=inttostr(hoztovari)+' piece';
  if gastronom<>1 then
  form1.Label13.caption:=inttostr(gastronom)+' pieces' else
  form1.Label13.caption:=inttostr(gastronom)+' piece';
  if restaurant<>1 then
  form1.Label14.caption:=inttostr(restaurant)+' pieces' else
  form1.Label14.caption:=inttostr(restaurant)+' piece';
  if apteka<>1 then
  form1.Label16.caption:=inttostr(apteka)+' pieces' else
  form1.Label16.caption:=inttostr(apteka)+' piece';
  if cinema<>1 then
  form1.Label17.caption:=inttostr(cinema)+' pieces' else
  form1.Label17.caption:=inttostr(cinema)+' piece';
  if cinemastudio<>1 then
  form1.Label18.caption:=inttostr(cinemastudio)+' pieces' else
  form1.Label18.caption:=inttostr(cinemastudio)+' piece';
  if hostel<>1 then
  form1.Label19.caption:=inttostr(hostel)+' pieces' else
  form1.Label19.caption:=inttostr(hostel)+' piece';
  if hotel<>1 then
  form1.Label20.caption:=inttostr(hotel)+' pieces' else
  form1.Label20.caption:=inttostr(hotel)+' piece';
  if TC<>1 then
  form1.Label21.caption:=inttostr(TC)+' pieces' else
  form1.Label21.caption:=inttostr(TC)+' piece';
  if autoservice<>1 then
  form1.Label22.caption:=inttostr(autoservice)+' pieces' else
  form1.Label22.caption:=inttostr(autoservice)+' piece';
  if fitness<>1 then
  form1.Label23.caption:=inttostr(fitness)+' pieces' else
  form1.Label23.caption:=inttostr(fitness)+' piece';
  if beauty<>1 then
  form1.Label24.caption:=inttostr(beauty)+' pieces' else
  form1.Label24.caption:=inttostr(beauty)+' piece';
  if stomatologia<>1 then
  form1.Label25.caption:=inttostr(stomatologia)+' pieces' else
  form1.Label25.caption:=inttostr(stomatologia)+' piece';
  if socnet<>1 then
  form1.Label26.caption:=inttostr(socnet)+' pieces' else
  form1.Label26.caption:=inttostr(socnet)+' piece';
  if bank<>1 then
  form1.Label27.caption:=inttostr(bank)+' pieces' else
  form1.Label27.caption:=inttostr(bank)+' piece';
  if blackgold<>1 then
  form1.Label28.caption:=inttostr(blackgold)+' pieces' else
  form1.Label28.caption:=inttostr(blackgold)+' piece';
  if va<>1 then
  form1.Label29.caption:=inttostr(va)+' pieces' else
  form1.Label29.caption:=inttostr(va)+' piece';
  form1.Label66.caption:='Your level of active profit';
  form1.Label65.caption:='Your level of passive profit';
  form1.Label2.caption:='Your level of XP';
  form1.statictext1.caption:='Businessmen simulator';
  form1.statictext8.caption:='Little kiosk';
  form1.statictext9.caption:='Household goods';
  form1.statictext10.caption:='Gastronome';
  form1.statictext19.caption:='Restaurant';
  form1.statictext11.caption:='Pharmacy';
  form1.statictext12.caption:='Cinema';
  form1.statictext24.caption:='GameDev studio';
  form1.statictext13.caption:='Hostel';
  form1.statictext14.caption:='Hotel';
  form1.statictext15.caption:='Shopping mall';
  form1.statictext17.caption:='Car wash';
  form1.statictext16.caption:='Fitness center';
  form1.statictext18.caption:='Beauty salon';
  form1.statictext20.caption:='Stomatology';
  form1.statictext23.caption:='Social network';
  form1.statictext21.caption:='Bank';
  form1.statictext22.caption:='Oil company';
  form1.statictext25.caption:='Your activity';
  form1.statictext43.caption:='Your value';
  form1.button2.caption:='Save';
  form1.button3.caption:='Load';
  form1.button4.caption:='Quit';
  form1.button5.caption:='Authors';
  form1.button1.caption:='Help';
  form1.button7.caption:='Statistic';
  form1.button9.caption:='Donate';
  form1.button10.caption:='Achievements';
  form1.button11.caption:='BugReport';
  form1.button31.caption:='Options';
  form1.button13.caption:='Buy';
  form1.button14.caption:='Buy';
  form1.button15.caption:='Buy';
  form1.button16.caption:='Buy';
  form1.button17.caption:='Buy';
  form1.button18.caption:='Buy';
  form1.button19.caption:='Buy';
  form1.button20.caption:='Buy';
  form1.button21.caption:='Buy';
  form1.button22.caption:='Buy';
  form1.button23.caption:='Buy';
  form1.button24.caption:='Buy';
  form1.button25.caption:='Buy';
  form1.button26.caption:='Buy';
  form1.button27.caption:='Buy';
  form1.button28.caption:='Buy';
  form1.button29.caption:='Buy';
  form1.button30.caption:='Buy';
  form1.button8.caption:='Lottery';
  form1.button6.caption:='Work';
  form1.radiobutton1.caption:='Rubles';
  form1.radiobutton2.caption:='Dollars';
  form1.radiobutton3.caption:='Euro';
  form1.radiobutton4.caption:='Yuan';
  form1.radiobutton5.caption:='Pounds';
  form2.button1.caption:='Back';
  form2.tabsheet1.caption:='Passive profit';
  form2.tabsheet2.caption:='Active profit';
  form2.tabsheet3.caption:='Money got';
  form2.tabsheet4.caption:='Little kiosk';
  form2.tabsheet5.caption:='Household goods';
  form2.tabsheet6.caption:='Gastronome';
  form2.tabsheet7.caption:='Restaurant';
  form2.tabsheet8.caption:='Pharmacy';
  form2.tabsheet9.caption:='Cinema';
  form2.tabsheet10.caption:='GameDev studio';
  form2.tabsheet11.caption:='Hostel';
  form2.tabsheet12.caption:='Hotel';
  form2.tabsheet13.caption:='Shopping mall';
  form2.tabsheet14.caption:='Car wash';
  form2.tabsheet15.caption:='Fitness center';
  form2.tabsheet16.caption:='Beauty salon';
  form2.tabsheet17.caption:='Stomatology';
  form2.tabsheet18.caption:='Social network';
  form2.tabsheet19.caption:='Bank';
  form2.tabsheet20.caption:='Oil company';
  form2.tabsheet21.caption:='Your activity';
  form2.tabsheet24.caption:='All activities';
  form2.tabsheet23.caption:='Other';
  form3.statictext1.caption:='Do you like the game? Wanna leave a message on the site?';
  form3.button1.caption:='Yes';
  form3.button2.caption:='Do not remind';
  form3.button3.caption:='Not now';
  form4.button1.caption:='Close in 15 seconds';
  form5.button1.caption:='Use';
  form5.label1.caption:='Put in the secret key';
  form6.label1.caption:='Which browser do you use?';
  form6.button4.caption:='Other one';
  form7.groupbox2.caption:='Background';
  form7.radiobutton9.caption:='Without background';
  form7.button1.caption:='Back to game';
  form1.caption:='Businessmen simulator';
  form2.caption:='Achievements';
  form3.caption:='Businessmen simulator';
  form4.caption:='Ads';
  form7.caption:='Options';
  language:='english';
  check:=0
end;

procedure TForm7.RadioButton14Click(Sender: TObject);
begin
  attentlang:='ATTENTION';
  competlang:='COMPETITION';
  form1.Label1.caption:='Menu';
  form1.Label3.caption:='Passive profit';
  form1.Label4.caption:='Active profit';
  if littlekiosk<>1 then
  form1.Label12.caption:=inttostr(littlekiosk)+' pieces' else
  form1.Label12.caption:=inttostr(littlekiosk)+' piece';
  form1.Label10.caption:='Currency';
  form1.Label8.caption:='Money that you have:';
  if hoztovari<>1 then
  form1.Label15.caption:=inttostr(hoztovari)+' pieces' else
  form1.Label15.caption:=inttostr(hoztovari)+' piece';
  if gastronom<>1 then
  form1.Label13.caption:=inttostr(gastronom)+' pieces' else
  form1.Label13.caption:=inttostr(gastronom)+' piece';
  if restaurant<>1 then
  form1.Label14.caption:=inttostr(restaurant)+' pieces' else
  form1.Label14.caption:=inttostr(restaurant)+' piece';
  if apteka<>1 then
  form1.Label16.caption:=inttostr(apteka)+' pieces' else
  form1.Label16.caption:=inttostr(apteka)+' piece';
  if cinema<>1 then
  form1.Label17.caption:=inttostr(cinema)+' pieces' else
  form1.Label17.caption:=inttostr(cinema)+' piece';
  if cinemastudio<>1 then
  form1.Label18.caption:=inttostr(cinemastudio)+' pieces' else
  form1.Label18.caption:=inttostr(cinemastudio)+' piece';
  if hostel<>1 then
  form1.Label19.caption:=inttostr(hostel)+' pieces' else
  form1.Label19.caption:=inttostr(hostel)+' piece';
  if hotel<>1 then
  form1.Label20.caption:=inttostr(hotel)+' pieces' else
  form1.Label20.caption:=inttostr(hotel)+' piece';
  if TC<>1 then
  form1.Label21.caption:=inttostr(TC)+' pieces' else
  form1.Label21.caption:=inttostr(TC)+' piece';
  if autoservice<>1 then
  form1.Label22.caption:=inttostr(autoservice)+' pieces' else
  form1.Label22.caption:=inttostr(autoservice)+' piece';
  if fitness<>1 then
  form1.Label23.caption:=inttostr(fitness)+' pieces' else
  form1.Label23.caption:=inttostr(fitness)+' piece';
  if beauty<>1 then
  form1.Label24.caption:=inttostr(beauty)+' pieces' else
  form1.Label24.caption:=inttostr(beauty)+' piece';
  if stomatologia<>1 then
  form1.Label25.caption:=inttostr(stomatologia)+' pieces' else
  form1.Label25.caption:=inttostr(stomatologia)+' piece';
  if socnet<>1 then
  form1.Label26.caption:=inttostr(socnet)+' pieces' else
  form1.Label26.caption:=inttostr(socnet)+' piece';
  if bank<>1 then
  form1.Label27.caption:=inttostr(bank)+' pieces' else
  form1.Label27.caption:=inttostr(bank)+' piece';
  if blackgold<>1 then
  form1.Label28.caption:=inttostr(blackgold)+' pieces' else
  form1.Label28.caption:=inttostr(blackgold)+' piece';
  if va<>1 then
  form1.Label29.caption:=inttostr(va)+' pieces' else
  form1.Label29.caption:=inttostr(va)+' piece';
  form1.Label66.caption:='Your level of active profit';
  form1.Label65.caption:='Your level of passive profit';
  form1.Label2.caption:='Your level of XP';
  form1.statictext1.caption:='Businessmen simulator';
  form1.statictext8.caption:='Little kiosk';
  form1.statictext9.caption:='Household goods';
  form1.statictext10.caption:='Gastronome';
  form1.statictext19.caption:='Restaurant';
  form1.statictext11.caption:='Pharmacy';
  form1.statictext12.caption:='Cinema';
  form1.statictext24.caption:='GameDev studio';
  form1.statictext13.caption:='Hostel';
  form1.statictext14.caption:='Hotel';
  form1.statictext15.caption:='Shopping mall';
  form1.statictext17.caption:='Car wash';
  form1.statictext16.caption:='Fitness center';
  form1.statictext18.caption:='Beauty salon';
  form1.statictext20.caption:='Stomatology';
  form1.statictext23.caption:='Social network';
  form1.statictext21.caption:='Bank';
  form1.statictext22.caption:='Oil company';
  form1.statictext25.caption:='Your activity';
  form1.statictext43.caption:='Your value';
  form1.button2.caption:='Save';
  form1.button3.caption:='Load';
  form1.button4.caption:='Quit';
  form1.button5.caption:='Authors';
  form1.button1.caption:='Help';
  form1.button7.caption:='Statistic';
  form1.button9.caption:='Donate';
  form1.button10.caption:='Achievements';
  form1.button11.caption:='BugReport';
  form1.button31.caption:='Options';
  form1.button13.caption:='Buy';
  form1.button14.caption:='Buy';
  form1.button15.caption:='Buy';
  form1.button16.caption:='Buy';
  form1.button17.caption:='Buy';
  form1.button18.caption:='Buy';
  form1.button19.caption:='Buy';
  form1.button20.caption:='Buy';
  form1.button21.caption:='Buy';
  form1.button22.caption:='Buy';
  form1.button23.caption:='Buy';
  form1.button24.caption:='Buy';
  form1.button25.caption:='Buy';
  form1.button26.caption:='Buy';
  form1.button27.caption:='Buy';
  form1.button28.caption:='Buy';
  form1.button29.caption:='Buy';
  form1.button30.caption:='Buy';
  form1.button8.caption:='Lottery';
  form1.button6.caption:='Work';
  form1.radiobutton1.caption:='Rubles';
  form1.radiobutton2.caption:='Dollars';
  form1.radiobutton3.caption:='Euro';
  form1.radiobutton4.caption:='Yuan';
  form1.radiobutton5.caption:='Pounds';
  form2.button1.caption:='Back';
  form2.tabsheet1.caption:='Passive profit';
  form2.tabsheet2.caption:='Active profit';
  form2.tabsheet3.caption:='Money got';
  form2.tabsheet4.caption:='Little kiosk';
  form2.tabsheet5.caption:='Household goods';
  form2.tabsheet6.caption:='Gastronome';
  form2.tabsheet7.caption:='Restaurant';
  form2.tabsheet8.caption:='Pharmacy';
  form2.tabsheet9.caption:='Cinema';
  form2.tabsheet10.caption:='GameDev studio';
  form2.tabsheet11.caption:='Hostel';
  form2.tabsheet12.caption:='Hotel';
  form2.tabsheet13.caption:='Shopping mall';
  form2.tabsheet14.caption:='Car wash';
  form2.tabsheet15.caption:='Fitness center';
  form2.tabsheet16.caption:='Beauty salon';
  form2.tabsheet17.caption:='Stomatology';
  form2.tabsheet18.caption:='Social network';
  form2.tabsheet19.caption:='Bank';
  form2.tabsheet20.caption:='Oil company';
  form2.tabsheet21.caption:='Your activity';
  form2.tabsheet24.caption:='All activities';
  form2.tabsheet23.caption:='Other';
  form3.statictext1.caption:='Do you like the game? Wanna leave a message on the site?';
  form3.button1.caption:='Yes';
  form3.button2.caption:='Do not remind';
  form3.button3.caption:='Not now';
  form4.button1.caption:='Close in 15 seconds';
  form5.button1.caption:='Use';
  form5.label1.caption:='Put in the secret key';
  form6.label1.caption:='Which browser do you use?';
  form6.button4.caption:='Other one';
  form7.groupbox2.caption:='Background';
  form7.radiobutton9.caption:='Without background';
  form7.button1.caption:='Back to game';
  form1.caption:='Businessmen simulator';
  form2.caption:='Achievements';
  form3.caption:='Businessmen simulator';
  form4.caption:='Ads';
  form7.caption:='Options';
  language:='afrikaans';
  check:=0
end;

procedure TForm7.RadioButton15Click(Sender: TObject);
begin
  attentlang:='DYBVFYBT!!!';
  competlang:='RJYREHC!!!';
  form1.Label1.caption:='Vty.';
  form1.Label3.caption:='Gfccbdysq lj[jl';
  form1.Label4.caption:='Frnbdysq lj[jl';
  check:=littlekiosk mod 100;
  case check of
  0: form1.label12.caption:=(inttostr(littlekiosk)+' iner');
  1: form1.label12.caption:=(inttostr(littlekiosk)+' inerf');
  2..4: form1.label12.caption:=(inttostr(littlekiosk)+' inerb');
  5..20: form1.label12.caption:=(inttostr(littlekiosk)+' iner');
  21: form1.label12.caption:=(inttostr(littlekiosk)+' inerf');
  22..24: form1.label12.caption:=(inttostr(littlekiosk)+' inerb');
  25..30: form1.label12.caption:=(inttostr(littlekiosk)+' iner');
  31: form1.label12.caption:=(inttostr(littlekiosk)+' inerf');
  32..34: form1.label12.caption:=(inttostr(littlekiosk)+' inerb');
  35..40: form1.label12.caption:=(inttostr(littlekiosk)+' iner');
  41: form1.label12.caption:=(inttostr(littlekiosk)+' inerf');
  42..44: form1.label12.caption:=(inttostr(littlekiosk)+' inerb');
  45..50: form1.label12.caption:=(inttostr(littlekiosk)+' iner');
  51: form1.label12.caption:=(inttostr(littlekiosk)+' inerf');
  52..54: form1.label12.caption:=(inttostr(littlekiosk)+' inerb');
  55..60: form1.label12.caption:=(inttostr(littlekiosk)+' iner');
  61: form1.label12.caption:=(inttostr(littlekiosk)+' inerf');
  62..64: form1.label12.caption:=(inttostr(littlekiosk)+' inerb');
  65..70: form1.label12.caption:=(inttostr(littlekiosk)+' iner');
  71: form1.label12.caption:=(inttostr(littlekiosk)+' inerf');
  72..74: form1.label12.caption:=(inttostr(littlekiosk)+' inerb');
  75..80: form1.label12.caption:=(inttostr(littlekiosk)+' iner');
  81: form1.label12.caption:=(inttostr(littlekiosk)+' inerf');
  82..84: form1.label12.caption:=(inttostr(littlekiosk)+' inerb');
  85..90: form1.label12.caption:=(inttostr(littlekiosk)+' iner');
  91: form1.label12.caption:=(inttostr(littlekiosk)+' inerf');
  92..94: form1.label12.caption:=(inttostr(littlekiosk)+' inerb');
  95..99: form1.label12.caption:=(inttostr(littlekiosk)+' iner');
  end;
  form1.Label10.caption:='Dfk.nf';
  form1.Label8.caption:='Dfit cjcnjzybt cjcnfdkztnm';
  check:=hoztovari mod 100;
  case check of
  0: form1.label15.caption:=(inttostr(hoztovari)+' iner');
  1: form1.label15.caption:=(inttostr(hoztovari)+' inerf');
  2..4: form1.label15.caption:=(inttostr(hoztovari)+' inerb');
  5..20: form1.label15.caption:=(inttostr(hoztovari)+' iner');
  21: form1.label15.caption:=(inttostr(hoztovari)+' inerf');
  22..24: form1.label15.caption:=(inttostr(hoztovari)+' inerb');
  25..30: form1.label15.caption:=(inttostr(hoztovari)+' iner');
  31: form1.label15.caption:=(inttostr(hoztovari)+' inerf');
  32..34: form1.label15.caption:=(inttostr(hoztovari)+' inerb');
  35..40: form1.label15.caption:=(inttostr(hoztovari)+' iner');
  41: form1.label15.caption:=(inttostr(hoztovari)+' inerf');
  42..44: form1.label15.caption:=(inttostr(hoztovari)+' inerb');
  45..50: form1.label15.caption:=(inttostr(hoztovari)+' iner');
  51: form1.label15.caption:=(inttostr(hoztovari)+' inerf');
  52..54: form1.label15.caption:=(inttostr(hoztovari)+' inerb');
  55..60: form1.label15.caption:=(inttostr(hoztovari)+' iner');
  61: form1.label15.caption:=(inttostr(hoztovari)+' inerf');
  62..64: form1.label15.caption:=(inttostr(hoztovari)+' inerb');
  65..70: form1.label15.caption:=(inttostr(hoztovari)+' iner');
  71: form1.label15.caption:=(inttostr(hoztovari)+' inerf');
  72..74: form1.label15.caption:=(inttostr(hoztovari)+' inerb');
  75..80: form1.label15.caption:=(inttostr(hoztovari)+' iner');
  81: form1.label15.caption:=(inttostr(hoztovari)+' inerf');
  82..84: form1.label15.caption:=(inttostr(hoztovari)+' inerb');
  85..90: form1.label15.caption:=(inttostr(hoztovari)+' iner');
  91: form1.label15.caption:=(inttostr(hoztovari)+' inerf');
  92..94: form1.label15.caption:=(inttostr(hoztovari)+' inerb');
  95..99: form1.label15.caption:=(inttostr(hoztovari)+' iner');
  end;
  check:=gastronom mod 100;
  case check of
  0: form1.label13.caption:=(inttostr(gastronom)+' iner');
  1: form1.label13.caption:=(inttostr(gastronom)+' inerf');
  2..4: form1.label13.caption:=(inttostr(gastronom)+' inerb');
  5..20: form1.label13.caption:=(inttostr(gastronom)+' iner');
  21: form1.label13.caption:=(inttostr(gastronom)+' inerf');
  22..24: form1.label13.caption:=(inttostr(gastronom)+' inerb');
  25..30: form1.label13.caption:=(inttostr(gastronom)+' iner');
  31: form1.label13.caption:=(inttostr(gastronom)+' inerf');
  32..34: form1.label13.caption:=(inttostr(gastronom)+' inerb');
  35..40: form1.label13.caption:=(inttostr(gastronom)+' iner');
  41: form1.label13.caption:=(inttostr(gastronom)+' inerf');
  42..44: form1.label13.caption:=(inttostr(gastronom)+' inerb');
  45..50: form1.label13.caption:=(inttostr(gastronom)+' iner');
  51: form1.label13.caption:=(inttostr(gastronom)+' inerf');
  52..54: form1.label13.caption:=(inttostr(gastronom)+' inerb');
  55..60: form1.label13.caption:=(inttostr(gastronom)+' iner');
  61: form1.label13.caption:=(inttostr(gastronom)+' inerf');
  62..64: form1.label13.caption:=(inttostr(gastronom)+' inerb');
  65..70: form1.label13.caption:=(inttostr(gastronom)+' iner');
  71: form1.label13.caption:=(inttostr(gastronom)+' inerf');
  72..74: form1.label13.caption:=(inttostr(gastronom)+' inerb');
  75..80: form1.label13.caption:=(inttostr(gastronom)+' iner');
  81: form1.label13.caption:=(inttostr(gastronom)+' inerf');
  82..84: form1.label13.caption:=(inttostr(gastronom)+' inerb');
  85..90: form1.label13.caption:=(inttostr(gastronom)+' iner');
  91: form1.label13.caption:=(inttostr(gastronom)+' inerf');
  92..94: form1.label13.caption:=(inttostr(gastronom)+' inerb');
  95..99: form1.label13.caption:=(inttostr(gastronom)+' iner');
  end;
  check:=restaurant mod 100;
  case check of
  0: form1.label14.caption:=(inttostr(restaurant)+' iner');
  1: form1.label14.caption:=(inttostr(restaurant)+' inerf');
  2..4: form1.label14.caption:=(inttostr(restaurant)+' inerb');
  5..20: form1.label14.caption:=(inttostr(restaurant)+' iner');
  21: form1.label14.caption:=(inttostr(restaurant)+' inerf');
  22..24: form1.label14.caption:=(inttostr(restaurant)+' inerb');
  25..30: form1.label14.caption:=(inttostr(restaurant)+' iner');
  31: form1.label14.caption:=(inttostr(restaurant)+' inerf');
  32..34: form1.label14.caption:=(inttostr(restaurant)+' inerb');
  35..40: form1.label14.caption:=(inttostr(restaurant)+' iner');
  41: form1.label14.caption:=(inttostr(restaurant)+' inerf');
  42..44: form1.label14.caption:=(inttostr(restaurant)+' inerb');
  45..50: form1.label14.caption:=(inttostr(restaurant)+' iner');
  51: form1.label14.caption:=(inttostr(restaurant)+' inerf');
  52..54: form1.label14.caption:=(inttostr(restaurant)+' inerb');
  55..60: form1.label14.caption:=(inttostr(restaurant)+' iner');
  61: form1.label14.caption:=(inttostr(restaurant)+' inerf');
  62..64: form1.label14.caption:=(inttostr(restaurant)+' inerb');
  65..70: form1.label14.caption:=(inttostr(restaurant)+' iner');
  71: form1.label14.caption:=(inttostr(restaurant)+' inerf');
  72..74: form1.label14.caption:=(inttostr(restaurant)+' inerb');
  75..80: form1.label14.caption:=(inttostr(restaurant)+' iner');
  81: form1.label14.caption:=(inttostr(restaurant)+' inerf');
  82..84: form1.label14.caption:=(inttostr(restaurant)+' inerb');
  85..90: form1.label14.caption:=(inttostr(restaurant)+' iner');
  91: form1.label14.caption:=(inttostr(restaurant)+' inerf');
  92..94: form1.label14.caption:=(inttostr(restaurant)+' inerb');
  95..99: form1.label14.caption:=(inttostr(restaurant)+' iner');
  end;
  check:=apteka mod 100;
  case check of
  0: form1.label16.caption:=(inttostr(apteka)+' iner');
  1: form1.label16.caption:=(inttostr(apteka)+' inerf');
  2..4: form1.label16.caption:=(inttostr(apteka)+' inerb');
  5..20: form1.label16.caption:=(inttostr(apteka)+' iner');
  21: form1.label16.caption:=(inttostr(apteka)+' inerf');
  22..24: form1.label16.caption:=(inttostr(apteka)+' inerb');
  25..30: form1.label16.caption:=(inttostr(apteka)+' iner');
  31: form1.label16.caption:=(inttostr(apteka)+' inerf');
  32..34: form1.label16.caption:=(inttostr(apteka)+' inerb');
  35..40: form1.label16.caption:=(inttostr(apteka)+' iner');
  41: form1.label16.caption:=(inttostr(apteka)+' inerf');
  42..44: form1.label16.caption:=(inttostr(apteka)+' inerb');
  45..50: form1.label16.caption:=(inttostr(apteka)+' iner');
  51: form1.label16.caption:=(inttostr(apteka)+' inerf');
  52..54: form1.label16.caption:=(inttostr(apteka)+' inerb');
  55..60: form1.label16.caption:=(inttostr(apteka)+' iner');
  61: form1.label16.caption:=(inttostr(apteka)+' inerf');
  62..64: form1.label16.caption:=(inttostr(apteka)+' inerb');
  65..70: form1.label16.caption:=(inttostr(apteka)+' iner');
  71: form1.label16.caption:=(inttostr(apteka)+' inerf');
  72..74: form1.label16.caption:=(inttostr(apteka)+' inerb');
  75..80: form1.label16.caption:=(inttostr(apteka)+' iner');
  81: form1.label16.caption:=(inttostr(apteka)+' inerf');
  82..84: form1.label16.caption:=(inttostr(apteka)+' inerb');
  85..90: form1.label16.caption:=(inttostr(apteka)+' iner');
  91: form1.label16.caption:=(inttostr(apteka)+' inerf');
  92..94: form1.label16.caption:=(inttostr(apteka)+' inerb');
  95..99: form1.label16.caption:=(inttostr(apteka)+' iner');
  end;
  check:=cinema mod 100;
  case check of
  0: form1.label17.caption:=(inttostr(cinema)+' iner');
  1: form1.label17.caption:=(inttostr(cinema)+' inerf');
  2..4: form1.label17.caption:=(inttostr(cinema)+' inerb');
  5..20: form1.label17.caption:=(inttostr(cinema)+' iner');
  21: form1.label17.caption:=(inttostr(cinema)+' inerf');
  22..24: form1.label17.caption:=(inttostr(cinema)+' inerb');
  25..30: form1.label17.caption:=(inttostr(cinema)+' iner');
  31: form1.label17.caption:=(inttostr(cinema)+' inerf');
  32..34: form1.label17.caption:=(inttostr(cinema)+' inerb');
  35..40: form1.label17.caption:=(inttostr(cinema)+' iner');
  41: form1.label17.caption:=(inttostr(cinema)+' inerf');
  42..44: form1.label17.caption:=(inttostr(cinema)+' inerb');
  45..50: form1.label17.caption:=(inttostr(cinema)+' iner');
  51: form1.label17.caption:=(inttostr(cinema)+' inerf');
  52..54: form1.label17.caption:=(inttostr(cinema)+' inerb');
  55..60: form1.label17.caption:=(inttostr(cinema)+' iner');
  61: form1.label17.caption:=(inttostr(cinema)+' inerf');
  62..64: form1.label17.caption:=(inttostr(cinema)+' inerb');
  65..70: form1.label17.caption:=(inttostr(cinema)+' iner');
  71: form1.label17.caption:=(inttostr(cinema)+' inerf');
  72..74: form1.label17.caption:=(inttostr(cinema)+' inerb');
  75..80: form1.label17.caption:=(inttostr(cinema)+' iner');
  81: form1.label17.caption:=(inttostr(cinema)+' inerf');
  82..84: form1.label17.caption:=(inttostr(cinema)+' inerb');
  85..90: form1.label17.caption:=(inttostr(cinema)+' iner');
  91: form1.label17.caption:=(inttostr(cinema)+' inerf');
  92..94: form1.label17.caption:=(inttostr(cinema)+' inerb');
  95..99: form1.label17.caption:=(inttostr(cinema)+' iner');
  end;
  check:=cinemastudio mod 100;
  case check of
  0: form1.label18.caption:=(inttostr(cinemastudio)+' iner');
  1: form1.label18.caption:=(inttostr(cinemastudio)+' inerf');
  2..4: form1.label18.caption:=(inttostr(cinemastudio)+' inerb');
  5..20: form1.label18.caption:=(inttostr(cinemastudio)+' iner');
  21: form1.label18.caption:=(inttostr(cinemastudio)+' inerf');
  22..24: form1.label18.caption:=(inttostr(cinemastudio)+' inerb');
  25..30: form1.label18.caption:=(inttostr(cinemastudio)+' iner');
  31: form1.label18.caption:=(inttostr(cinemastudio)+' inerf');
  32..34: form1.label18.caption:=(inttostr(cinemastudio)+' inerb');
  35..40: form1.label18.caption:=(inttostr(cinemastudio)+' iner');
  41: form1.label18.caption:=(inttostr(cinemastudio)+' inerf');
  42..44: form1.label18.caption:=(inttostr(cinemastudio)+' inerb');
  45..50: form1.label18.caption:=(inttostr(cinemastudio)+' iner');
  51: form1.label18.caption:=(inttostr(cinemastudio)+' inerf');
  52..54: form1.label18.caption:=(inttostr(cinemastudio)+' inerb');
  55..60: form1.label18.caption:=(inttostr(cinemastudio)+' iner');
  61: form1.label18.caption:=(inttostr(cinemastudio)+' inerf');
  62..64: form1.label18.caption:=(inttostr(cinemastudio)+' inerb');
  65..70: form1.label18.caption:=(inttostr(cinemastudio)+' iner');
  71: form1.label18.caption:=(inttostr(cinemastudio)+' inerf');
  72..74: form1.label18.caption:=(inttostr(cinemastudio)+' inerb');
  75..80: form1.label18.caption:=(inttostr(cinemastudio)+' iner');
  81: form1.label18.caption:=(inttostr(cinemastudio)+' inerf');
  82..84: form1.label18.caption:=(inttostr(cinemastudio)+' inerb');
  85..90: form1.label18.caption:=(inttostr(cinemastudio)+' iner');
  91: form1.label18.caption:=(inttostr(cinemastudio)+' inerf');
  92..94: form1.label18.caption:=(inttostr(cinemastudio)+' inerb');
  95..99: form1.label18.caption:=(inttostr(cinemastudio)+' iner');
  end;
  check:=hostel mod 100;
  case check of
  0: form1.label19.caption:=(inttostr(hostel)+' iner');
  1: form1.label19.caption:=(inttostr(hostel)+' inerf');
  2..4: form1.label19.caption:=(inttostr(hostel)+' inerb');
  5..20: form1.label19.caption:=(inttostr(hostel)+' iner');
  21: form1.label19.caption:=(inttostr(hostel)+' inerf');
  22..24: form1.label19.caption:=(inttostr(hostel)+' inerb');
  25..30: form1.label19.caption:=(inttostr(hostel)+' iner');
  31: form1.label19.caption:=(inttostr(hostel)+' inerf');
  32..34: form1.label19.caption:=(inttostr(hostel)+' inerb');
  35..40: form1.label19.caption:=(inttostr(hostel)+' iner');
  41: form1.label19.caption:=(inttostr(hostel)+' inerf');
  42..44: form1.label19.caption:=(inttostr(hostel)+' inerb');
  45..50: form1.label19.caption:=(inttostr(hostel)+' iner');
  51: form1.label19.caption:=(inttostr(hostel)+' inerf');
  52..54: form1.label19.caption:=(inttostr(hostel)+' inerb');
  55..60: form1.label19.caption:=(inttostr(hostel)+' iner');
  61: form1.label19.caption:=(inttostr(hostel)+' inerf');
  62..64: form1.label19.caption:=(inttostr(hostel)+' inerb');
  65..70: form1.label19.caption:=(inttostr(hostel)+' iner');
  71: form1.label19.caption:=(inttostr(hostel)+' inerf');
  72..74: form1.label19.caption:=(inttostr(hostel)+' inerb');
  75..80: form1.label19.caption:=(inttostr(hostel)+' iner');
  81: form1.label19.caption:=(inttostr(hostel)+' inerf');
  82..84: form1.label19.caption:=(inttostr(hostel)+' inerb');
  85..90: form1.label19.caption:=(inttostr(hostel)+' iner');
  91: form1.label19.caption:=(inttostr(hostel)+' inerf');
  92..94: form1.label19.caption:=(inttostr(hostel)+' inerb');
  95..99: form1.label19.caption:=(inttostr(hostel)+' iner');
  end;
  check:=hotel mod 100;
  case check of
  0: form1.label20.caption:=(inttostr(hotel)+' iner');
  1: form1.label20.caption:=(inttostr(hotel)+' inerf');
  2..4: form1.label20.caption:=(inttostr(hotel)+' inerb');
  5..20: form1.label20.caption:=(inttostr(hotel)+' iner');
  21: form1.label20.caption:=(inttostr(hotel)+' inerf');
  22..24: form1.label20.caption:=(inttostr(hotel)+' inerb');
  25..30: form1.label20.caption:=(inttostr(hotel)+' iner');
  31: form1.label20.caption:=(inttostr(hotel)+' inerf');
  32..34: form1.label20.caption:=(inttostr(hotel)+' inerb');
  35..40: form1.label20.caption:=(inttostr(hotel)+' iner');
  41: form1.label20.caption:=(inttostr(hotel)+' inerf');
  42..44: form1.label20.caption:=(inttostr(hotel)+' inerb');
  45..50: form1.label20.caption:=(inttostr(hotel)+' iner');
  51: form1.label20.caption:=(inttostr(hotel)+' inerf');
  52..54: form1.label20.caption:=(inttostr(hotel)+' inerb');
  55..60: form1.label20.caption:=(inttostr(hotel)+' iner');
  61: form1.label20.caption:=(inttostr(hotel)+' inerf');
  62..64: form1.label20.caption:=(inttostr(hotel)+' inerb');
  65..70: form1.label20.caption:=(inttostr(hotel)+' iner');
  71: form1.label20.caption:=(inttostr(hotel)+' inerf');
  72..74: form1.label20.caption:=(inttostr(hotel)+' inerb');
  75..80: form1.label20.caption:=(inttostr(hotel)+' iner');
  81: form1.label20.caption:=(inttostr(hotel)+' inerf');
  82..84: form1.label20.caption:=(inttostr(hotel)+' inerb');
  85..90: form1.label20.caption:=(inttostr(hotel)+' iner');
  91: form1.label20.caption:=(inttostr(hotel)+' inerf');
  92..94: form1.label20.caption:=(inttostr(hotel)+' inerb');
  95..99: form1.label20.caption:=(inttostr(hotel)+' iner');
  end;
  check:=TC mod 100;
  case check of
  0: form1.label21.caption:=(inttostr(TC)+' iner');
  1: form1.label21.caption:=(inttostr(TC)+' inerf');
  2..4: form1.label21.caption:=(inttostr(TC)+' inerb');
  5..20: form1.label21.caption:=(inttostr(TC)+' iner');
  21: form1.label21.caption:=(inttostr(TC)+' inerf');
  22..24: form1.label21.caption:=(inttostr(TC)+' inerb');
  25..30: form1.label21.caption:=(inttostr(TC)+' iner');
  31: form1.label21.caption:=(inttostr(TC)+' inerf');
  32..34: form1.label21.caption:=(inttostr(TC)+' inerb');
  35..40: form1.label21.caption:=(inttostr(TC)+' iner');
  41: form1.label21.caption:=(inttostr(TC)+' inerf');
  42..44: form1.label21.caption:=(inttostr(TC)+' inerb');
  45..50: form1.label21.caption:=(inttostr(TC)+' iner');
  51: form1.label21.caption:=(inttostr(TC)+' inerf');
  52..54: form1.label21.caption:=(inttostr(TC)+' inerb');
  55..60: form1.label21.caption:=(inttostr(TC)+' iner');
  61: form1.label21.caption:=(inttostr(TC)+' inerf');
  62..64: form1.label21.caption:=(inttostr(TC)+' inerb');
  65..70: form1.label21.caption:=(inttostr(TC)+' iner');
  71: form1.label21.caption:=(inttostr(TC)+' inerf');
  72..74: form1.label21.caption:=(inttostr(TC)+' inerb');
  75..80: form1.label21.caption:=(inttostr(TC)+' iner');
  81: form1.label21.caption:=(inttostr(TC)+' inerf');
  82..84: form1.label21.caption:=(inttostr(TC)+' inerb');
  85..90: form1.label21.caption:=(inttostr(TC)+' iner');
  91: form1.label21.caption:=(inttostr(TC)+' inerf');
  92..94: form1.label21.caption:=(inttostr(TC)+' inerb');
  95..99: form1.label21.caption:=(inttostr(TC)+' iner');
  end;
  check:=autoservice mod 100;
  case check of
  0: form1.label22.caption:=(inttostr(autoservice)+' iner');
  1: form1.label22.caption:=(inttostr(autoservice)+' inerf');
  2..4: form1.label22.caption:=(inttostr(autoservice)+' inerb');
  5..20: form1.label22.caption:=(inttostr(autoservice)+' iner');
  21: form1.label22.caption:=(inttostr(autoservice)+' inerf');
  22..24: form1.label22.caption:=(inttostr(autoservice)+' inerb');
  25..30: form1.label22.caption:=(inttostr(autoservice)+' iner');
  31: form1.label22.caption:=(inttostr(autoservice)+' inerf');
  32..34: form1.label22.caption:=(inttostr(autoservice)+' inerb');
  35..40: form1.label22.caption:=(inttostr(autoservice)+' iner');
  41: form1.label22.caption:=(inttostr(autoservice)+' inerf');
  42..44: form1.label22.caption:=(inttostr(autoservice)+' inerb');
  45..50: form1.label22.caption:=(inttostr(autoservice)+' iner');
  51: form1.label22.caption:=(inttostr(autoservice)+' inerf');
  52..54: form1.label22.caption:=(inttostr(autoservice)+' inerb');
  55..60: form1.label22.caption:=(inttostr(autoservice)+' iner');
  61: form1.label22.caption:=(inttostr(autoservice)+' inerf');
  62..64: form1.label22.caption:=(inttostr(autoservice)+' inerb');
  65..70: form1.label22.caption:=(inttostr(autoservice)+' iner');
  71: form1.label22.caption:=(inttostr(autoservice)+' inerf');
  72..74: form1.label22.caption:=(inttostr(autoservice)+' inerb');
  75..80: form1.label22.caption:=(inttostr(autoservice)+' iner');
  81: form1.label22.caption:=(inttostr(autoservice)+' inerf');
  82..84: form1.label22.caption:=(inttostr(autoservice)+' inerb');
  85..90: form1.label22.caption:=(inttostr(autoservice)+' iner');
  91: form1.label22.caption:=(inttostr(autoservice)+' inerf');
  92..94: form1.label22.caption:=(inttostr(autoservice)+' inerb');
  95..99: form1.label22.caption:=(inttostr(autoservice)+' iner');
  end;
  check:=fitness mod 100;
  case check of
  0: form1.label23.caption:=(inttostr(fitness)+' iner');
  1: form1.label23.caption:=(inttostr(fitness)+' inerf');
  2..4: form1.label23.caption:=(inttostr(fitness)+' inerb');
  5..20: form1.label23.caption:=(inttostr(fitness)+' iner');
  21: form1.label23.caption:=(inttostr(fitness)+' inerf');
  22..24: form1.label23.caption:=(inttostr(fitness)+' inerb');
  25..30: form1.label23.caption:=(inttostr(fitness)+' iner');
  31: form1.label23.caption:=(inttostr(fitness)+' inerf');
  32..34: form1.label23.caption:=(inttostr(fitness)+' inerb');
  35..40: form1.label23.caption:=(inttostr(fitness)+' iner');
  41: form1.label23.caption:=(inttostr(fitness)+' inerf');
  42..44: form1.label23.caption:=(inttostr(fitness)+' inerb');
  45..50: form1.label23.caption:=(inttostr(fitness)+' iner');
  51: form1.label23.caption:=(inttostr(fitness)+' inerf');
  52..54: form1.label23.caption:=(inttostr(fitness)+' inerb');
  55..60: form1.label23.caption:=(inttostr(fitness)+' iner');
  61: form1.label23.caption:=(inttostr(fitness)+' inerf');
  62..64: form1.label23.caption:=(inttostr(fitness)+' inerb');
  65..70: form1.label23.caption:=(inttostr(fitness)+' iner');
  71: form1.label23.caption:=(inttostr(fitness)+' inerf');
  72..74: form1.label23.caption:=(inttostr(fitness)+' inerb');
  75..80: form1.label23.caption:=(inttostr(fitness)+' iner');
  81: form1.label23.caption:=(inttostr(fitness)+' inerf');
  82..84: form1.label23.caption:=(inttostr(fitness)+' inerb');
  85..90: form1.label23.caption:=(inttostr(fitness)+' iner');
  91: form1.label23.caption:=(inttostr(fitness)+' inerf');
  92..94: form1.label23.caption:=(inttostr(fitness)+' inerb');
  95..99: form1.label23.caption:=(inttostr(fitness)+' iner');
  end;
  check:=beauty mod 100;
  case check of
  0: form1.label24.caption:=(inttostr(beauty)+' iner');
  1: form1.label24.caption:=(inttostr(beauty)+' inerf');
  2..4: form1.label24.caption:=(inttostr(beauty)+' inerb');
  5..20: form1.label24.caption:=(inttostr(beauty)+' iner');
  21: form1.label24.caption:=(inttostr(beauty)+' inerf');
  22..24: form1.label24.caption:=(inttostr(beauty)+' inerb');
  25..30: form1.label24.caption:=(inttostr(beauty)+' iner');
  31: form1.label24.caption:=(inttostr(beauty)+' inerf');
  32..34: form1.label24.caption:=(inttostr(beauty)+' inerb');
  35..40: form1.label24.caption:=(inttostr(beauty)+' iner');
  41: form1.label24.caption:=(inttostr(beauty)+' inerf');
  42..44: form1.label24.caption:=(inttostr(beauty)+' inerb');
  45..50: form1.label24.caption:=(inttostr(beauty)+' iner');
  51: form1.label24.caption:=(inttostr(beauty)+' inerf');
  52..54: form1.label24.caption:=(inttostr(beauty)+' inerb');
  55..60: form1.label24.caption:=(inttostr(beauty)+' iner');
  61: form1.label24.caption:=(inttostr(beauty)+' inerf');
  62..64: form1.label24.caption:=(inttostr(beauty)+' inerb');
  65..70: form1.label24.caption:=(inttostr(beauty)+' iner');
  71: form1.label24.caption:=(inttostr(beauty)+' inerf');
  72..74: form1.label24.caption:=(inttostr(beauty)+' inerb');
  75..80: form1.label24.caption:=(inttostr(beauty)+' iner');
  81: form1.label24.caption:=(inttostr(beauty)+' inerf');
  82..84: form1.label24.caption:=(inttostr(beauty)+' inerb');
  85..90: form1.label24.caption:=(inttostr(beauty)+' iner');
  91: form1.label24.caption:=(inttostr(beauty)+' inerf');
  92..94: form1.label24.caption:=(inttostr(beauty)+' inerb');
  95..99: form1.label24.caption:=(inttostr(beauty)+' iner');
  end;
  check:=stomatologia mod 100;
  case check of
  0: form1.label25.caption:=(inttostr(stomatologia)+' iner');
  1: form1.label25.caption:=(inttostr(stomatologia)+' inerf');
  2..4: form1.label25.caption:=(inttostr(stomatologia)+' inerb');
  5..20: form1.label25.caption:=(inttostr(stomatologia)+' iner');
  21: form1.label25.caption:=(inttostr(stomatologia)+' inerf');
  22..24: form1.label25.caption:=(inttostr(stomatologia)+' inerb');
  25..30: form1.label25.caption:=(inttostr(stomatologia)+' iner');
  31: form1.label25.caption:=(inttostr(stomatologia)+' inerf');
  32..34: form1.label25.caption:=(inttostr(stomatologia)+' inerb');
  35..40: form1.label25.caption:=(inttostr(stomatologia)+' iner');
  41: form1.label25.caption:=(inttostr(stomatologia)+' inerf');
  42..44: form1.label25.caption:=(inttostr(stomatologia)+' inerb');
  45..50: form1.label25.caption:=(inttostr(stomatologia)+' iner');
  51: form1.label25.caption:=(inttostr(stomatologia)+' inerf');
  52..54: form1.label25.caption:=(inttostr(stomatologia)+' inerb');
  55..60: form1.label25.caption:=(inttostr(stomatologia)+' iner');
  61: form1.label25.caption:=(inttostr(stomatologia)+' inerf');
  62..64: form1.label25.caption:=(inttostr(stomatologia)+' inerb');
  65..70: form1.label25.caption:=(inttostr(stomatologia)+' iner');
  71: form1.label25.caption:=(inttostr(stomatologia)+' inerf');
  72..74: form1.label25.caption:=(inttostr(stomatologia)+' inerb');
  75..80: form1.label25.caption:=(inttostr(stomatologia)+' iner');
  81: form1.label25.caption:=(inttostr(stomatologia)+' inerf');
  82..84: form1.label25.caption:=(inttostr(stomatologia)+' inerb');
  85..90: form1.label25.caption:=(inttostr(stomatologia)+' iner');
  91: form1.label25.caption:=(inttostr(stomatologia)+' inerf');
  92..94: form1.label25.caption:=(inttostr(stomatologia)+' inerb');
  95..99: form1.label25.caption:=(inttostr(stomatologia)+' iner');
  end;
  check:=socnet mod 100;
  case check of
  0: form1.label26.caption:=(inttostr(socnet)+' iner');
  1: form1.label26.caption:=(inttostr(socnet)+' inerf');
  2..4: form1.label26.caption:=(inttostr(socnet)+' inerb');
  5..20: form1.label26.caption:=(inttostr(socnet)+' iner');
  21: form1.label26.caption:=(inttostr(socnet)+' inerf');
  22..24: form1.label26.caption:=(inttostr(socnet)+' inerb');
  25..30: form1.label26.caption:=(inttostr(socnet)+' iner');
  31: form1.label26.caption:=(inttostr(socnet)+' inerf');
  32..34: form1.label26.caption:=(inttostr(socnet)+' inerb');
  35..40: form1.label26.caption:=(inttostr(socnet)+' iner');
  41: form1.label26.caption:=(inttostr(socnet)+' inerf');
  42..44: form1.label26.caption:=(inttostr(socnet)+' inerb');
  45..50: form1.label26.caption:=(inttostr(socnet)+' iner');
  51: form1.label26.caption:=(inttostr(socnet)+' inerf');
  52..54: form1.label26.caption:=(inttostr(socnet)+' inerb');
  55..60: form1.label26.caption:=(inttostr(socnet)+' iner');
  61: form1.label26.caption:=(inttostr(socnet)+' inerf');
  62..64: form1.label26.caption:=(inttostr(socnet)+' inerb');
  65..70: form1.label26.caption:=(inttostr(socnet)+' iner');
  71: form1.label26.caption:=(inttostr(socnet)+' inerf');
  72..74: form1.label26.caption:=(inttostr(socnet)+' inerb');
  75..80: form1.label26.caption:=(inttostr(socnet)+' iner');
  81: form1.label26.caption:=(inttostr(socnet)+' inerf');
  82..84: form1.label26.caption:=(inttostr(socnet)+' inerb');
  85..90: form1.label26.caption:=(inttostr(socnet)+' iner');
  91: form1.label26.caption:=(inttostr(socnet)+' inerf');
  92..94: form1.label26.caption:=(inttostr(socnet)+' inerb');
  95..99: form1.label26.caption:=(inttostr(socnet)+' iner');
  end;
  check:=bank mod 100;
  case check of
  0: form1.label27.caption:=(inttostr(bank)+' iner');
  1: form1.label27.caption:=(inttostr(bank)+' inerf');
  2..4: form1.label27.caption:=(inttostr(bank)+' inerb');
  5..20: form1.label27.caption:=(inttostr(bank)+' iner');
  21: form1.label27.caption:=(inttostr(bank)+' inerf');
  22..24: form1.label27.caption:=(inttostr(bank)+' inerb');
  25..30: form1.label27.caption:=(inttostr(bank)+' iner');
  31: form1.label27.caption:=(inttostr(bank)+' inerf');
  32..34: form1.label27.caption:=(inttostr(bank)+' inerb');
  35..40: form1.label27.caption:=(inttostr(bank)+' iner');
  41: form1.label27.caption:=(inttostr(bank)+' inerf');
  42..44: form1.label27.caption:=(inttostr(bank)+' inerb');
  45..50: form1.label27.caption:=(inttostr(bank)+' iner');
  51: form1.label27.caption:=(inttostr(bank)+' inerf');
  52..54: form1.label27.caption:=(inttostr(bank)+' inerb');
  55..60: form1.label27.caption:=(inttostr(bank)+' iner');
  61: form1.label27.caption:=(inttostr(bank)+' inerf');
  62..64: form1.label27.caption:=(inttostr(bank)+' inerb');
  65..70: form1.label27.caption:=(inttostr(bank)+' iner');
  71: form1.label27.caption:=(inttostr(bank)+' inerf');
  72..74: form1.label27.caption:=(inttostr(bank)+' inerb');
  75..80: form1.label27.caption:=(inttostr(bank)+' iner');
  81: form1.label27.caption:=(inttostr(bank)+' inerf');
  82..84: form1.label27.caption:=(inttostr(bank)+' inerb');
  85..90: form1.label27.caption:=(inttostr(bank)+' iner');
  91: form1.label27.caption:=(inttostr(bank)+' inerf');
  92..94: form1.label27.caption:=(inttostr(bank)+' inerb');
  95..99: form1.label27.caption:=(inttostr(bank)+' iner');
  end;
  check:=blackgold mod 100;
  case check of
  0: form1.label28.caption:=(inttostr(blackgold)+' iner');
  1: form1.label28.caption:=(inttostr(blackgold)+' inerf');
  2..4: form1.label28.caption:=(inttostr(blackgold)+' inerb');
  5..20: form1.label28.caption:=(inttostr(blackgold)+' iner');
  21: form1.label28.caption:=(inttostr(blackgold)+' inerf');
  22..24: form1.label28.caption:=(inttostr(blackgold)+' inerb');
  25..30: form1.label28.caption:=(inttostr(blackgold)+' iner');
  31: form1.label28.caption:=(inttostr(blackgold)+' inerf');
  32..34: form1.label28.caption:=(inttostr(blackgold)+' inerb');
  35..40: form1.label28.caption:=(inttostr(blackgold)+' iner');
  41: form1.label28.caption:=(inttostr(blackgold)+' inerf');
  42..44: form1.label28.caption:=(inttostr(blackgold)+' inerb');
  45..50: form1.label28.caption:=(inttostr(blackgold)+' iner');
  51: form1.label28.caption:=(inttostr(blackgold)+' inerf');
  52..54: form1.label28.caption:=(inttostr(blackgold)+' inerb');
  55..60: form1.label28.caption:=(inttostr(blackgold)+' iner');
  61: form1.label28.caption:=(inttostr(blackgold)+' inerf');
  62..64: form1.label28.caption:=(inttostr(blackgold)+' inerb');
  65..70: form1.label28.caption:=(inttostr(blackgold)+' iner');
  71: form1.label28.caption:=(inttostr(blackgold)+' inerf');
  72..74: form1.label28.caption:=(inttostr(blackgold)+' inerb');
  75..80: form1.label28.caption:=(inttostr(blackgold)+' iner');
  81: form1.label28.caption:=(inttostr(blackgold)+' inerf');
  82..84: form1.label28.caption:=(inttostr(blackgold)+' inerb');
  85..90: form1.label28.caption:=(inttostr(blackgold)+' iner');
  91: form1.label28.caption:=(inttostr(blackgold)+' inerf');
  92..94: form1.label28.caption:=(inttostr(blackgold)+' inerb');
  95..99: form1.label28.caption:=(inttostr(blackgold)+' iner');
  end;
  check:=va mod 100;
  case check of
  0: form1.label12.caption:=(inttostr(va)+' iner');
  1: form1.label12.caption:=(inttostr(va)+' inerf');
  2..4: form1.label12.caption:=(inttostr(va)+' inerb');
  5..20: form1.label12.caption:=(inttostr(va)+' iner');
  21: form1.label12.caption:=(inttostr(va)+' inerf');
  22..24: form1.label12.caption:=(inttostr(va)+' inerb');
  25..30: form1.label12.caption:=(inttostr(va)+' iner');
  31: form1.label12.caption:=(inttostr(va)+' inerf');
  32..34: form1.label12.caption:=(inttostr(va)+' inerb');
  35..40: form1.label12.caption:=(inttostr(va)+' iner');
  41: form1.label12.caption:=(inttostr(va)+' inerf');
  42..44: form1.label12.caption:=(inttostr(va)+' inerb');
  45..50: form1.label12.caption:=(inttostr(va)+' iner');
  51: form1.label12.caption:=(inttostr(va)+' inerf');
  52..54: form1.label12.caption:=(inttostr(va)+' inerb');
  55..60: form1.label12.caption:=(inttostr(va)+' iner');
  61: form1.label12.caption:=(inttostr(va)+' inerf');
  62..64: form1.label12.caption:=(inttostr(va)+' inerb');
  65..70: form1.label12.caption:=(inttostr(va)+' iner');
  71: form1.label12.caption:=(inttostr(va)+' inerf');
  72..74: form1.label12.caption:=(inttostr(va)+' inerb');
  75..80: form1.label12.caption:=(inttostr(va)+' iner');
  81: form1.label12.caption:=(inttostr(va)+' inerf');
  82..84: form1.label12.caption:=(inttostr(va)+' inerb');
  85..90: form1.label12.caption:=(inttostr(va)+' iner');
  91: form1.label12.caption:=(inttostr(va)+' inerf');
  92..94: form1.label12.caption:=(inttostr(va)+' inerb');
  95..99: form1.label12.caption:=(inttostr(va)+' iner');
  end;
  form1.Label66.caption:='Dfi ehjdtym frn/ lj[jlf';
  form1.Label65.caption:='Dfi ehjdtym gfcc/ lj[jlf';
  form1.Label2.caption:='Dfi ehjdtym jgsnf';
  form1.statictext1.caption:='Cbvekznjh ,bpytcvtyf';
  form1.statictext8.caption:='Vfktymrbq rbjcr';
  form1.statictext9.caption:='{jpnjdfhs';
  form1.statictext10.caption:='Ufcnhjyjv';
  form1.statictext19.caption:='Htcnjhfy';
  form1.statictext11.caption:='Fgntrf';
  form1.statictext12.caption:='Rbyjntfnh';
  form1.statictext24.caption:='Cnelbz utqvltdf';
  form1.statictext13.caption:='{jcntk';
  form1.statictext14.caption:='Jntkm';
  form1.statictext15.caption:='Njhujdsq wtynh';
  form1.statictext17.caption:='Fdnjcthdbc';
  form1.statictext16.caption:='Abnytc-wtynh';
  form1.statictext18.caption:='Cfkjy rhfcjns';
  form1.statictext20.caption:='Cnjvfnjkjubz';
  form1.statictext23.caption:='Cjwbfkmyfz ctnm';
  form1.statictext21.caption:='<fyr';
  form1.statictext22.caption:='Ytantrjvgfybz';
  form1.statictext25.caption:='Dfif frnbdyjcnm';
  form1.statictext43.caption:='Dfif cnjbvjcnm';
  form1.button2.caption:='Cj[hfybnm';
  form1.button3.caption:='Pfuhepbnm';
  form1.button4.caption:='Ds[jl';
  form1.button5.caption:='Fdnjhs';
  form1.button1.caption:='Cghfdrf';
  form1.button7.caption:='Cnfnbcnbrf';
  form1.button9.caption:='Gj;thndjdfnm';
  form1.button10.caption:='Fxbdrb';
  form1.button11.caption:='<fuHtgjhn';
  form1.button31.caption:='Yfcnhjqrb';
  form1.button13.caption:='Regbnm';
  form1.button14.caption:='Regbnm';
  form1.button15.caption:='Regbnm';
  form1.button16.caption:='Regbnm';
  form1.button17.caption:='Regbnm';
  form1.button18.caption:='Regbnm';
  form1.button19.caption:='Regbnm';
  form1.button20.caption:='Regbnm';
  form1.button21.caption:='Regbnm';
  form1.button22.caption:='Regbnm';
  form1.button23.caption:='Regbnm';
  form1.button24.caption:='Regbnm';
  form1.button25.caption:='Regbnm';
  form1.button26.caption:='Regbnm';
  form1.button27.caption:='Regbnm';
  form1.button28.caption:='Regbnm';
  form1.button29.caption:='Regbnm';
  form1.button30.caption:='Regbnm';
  form1.button8.caption:='Kjnthtz';
  form1.button6.caption:='Hf,jnfnm';
  form1.radiobutton1.caption:='He,kb';
  form1.radiobutton2.caption:='Ljkkfhs';
  form1.radiobutton3.caption:='Tdhj';
  form1.radiobutton4.caption:='>fyb';
  form1.radiobutton5.caption:='Aeyns Cnthk/';
  form2.button1.caption:='Yfpfl';
  form2.tabsheet1.caption:='Gfccbdysq lj[jl';
  form2.tabsheet2.caption:='Frnbdysq lj[jl';
  form2.tabsheet3.caption:='Ltymub yf herf[';
  form2.tabsheet4.caption:='Vfktymrbq rbjcr';
  form2.tabsheet5.caption:='{jpnjdfhs';
  form2.tabsheet6.caption:='Ufcnhjyjv';
  form2.tabsheet7.caption:='Htcnjhfy';
  form2.tabsheet8.caption:='Fgntrf';
  form2.tabsheet9.caption:='Rbyjntfnh';
  form2.tabsheet10.caption:='Cnelbz utqvltdf';
  form2.tabsheet11.caption:='{jcntk';
  form2.tabsheet12.caption:='Jntkm';
  form2.tabsheet13.caption:='Njhujdsq wtymj';
  form2.tabsheet14.caption:='Fdnjcthdbc';
  form2.tabsheet15.caption:='Abnytc-wtynh';
  form2.tabsheet16.caption:='Cfkjy rhfcjns';
  form2.tabsheet17.caption:='Cnjvfnjkjubz';
  form2.tabsheet18.caption:='Cjwbfkmyfz ctnm';
  form2.tabsheet19.caption:='<fyr';
  form2.tabsheet20.caption:='Ytantrjvgfybz';
  form2.tabsheet21.caption:='Dfif frnbdyjcnm';
  form2.tabsheet24.caption:='Dct frnbdyjcnb';
  form2.tabsheet23.caption:='Lheujt';
  form3.statictext1.caption:='Yhfdbncz buhf& Jcnfdbnm jnpsd yf cfqnt&';
  form3.button1.caption:='Lf';
  form3.button2.caption:='<jkmit yt yfgjvbyfnm';
  form3.button3.caption:='Yt ctqxfc';
  form4.button1.caption:='Pfrhsnm xthtp 15 ctreyl';
  form5.button1.caption:='Ghbvtybnm';
  form5.label1.caption:='Ddtlbnt ctrhtnysq rk.x';
  form6.label1.caption:='Rfrbv ,hfepthjv ns gjkmpetimcz&';
  form6.button4.caption:='Lheujq';
  form7.groupbox2.caption:='Ajy';
  form7.radiobutton9.caption:='<tp ajyf';
  form7.button1.caption:='Yfpfl d buhe';
  form1.caption:='Cbvekznjh ,bpytcvtyf';
  form2.caption:='Fxbdrb';
  form3.caption:='Cbvekznjh ,bpytcvtyf';
  form4.caption:='Htrkfvf';
  form7.caption:='Yfcnhjqrb';
  language:='wrongkey';
  check:=0;
end;

procedure TForm7.RadioButton19Click(Sender: TObject);
begin
  attentlang:='UPPMÄRKSAMHET';
  competlang:='KONKURRENS';
  form1.Label1.caption:='Meny';
  form1.Label3.caption:='Passiva vinst';
  form1.Label4.caption:='Activa vinst';
  if littlekiosk<>1 then
  form1.Label12.caption:=inttostr(littlekiosk)+' bitar' else
  form1.Label12.caption:=inttostr(littlekiosk)+' stycke';
  form1.Label10.caption:='Valuta';
  form1.Label8.caption:='Pengar som du har:';
  if hoztovari<>1 then
  form1.Label15.caption:=inttostr(hoztovari)+' bitar' else
  form1.Label15.caption:=inttostr(hoztovari)+' stycke';
  if gastronom<>1 then
  form1.Label13.caption:=inttostr(gastronom)+' bitar' else
  form1.Label13.caption:=inttostr(gastronom)+' stycke';
  if restaurant<>1 then
  form1.Label14.caption:=inttostr(restaurant)+' bitar' else
  form1.Label14.caption:=inttostr(restaurant)+' stycke';
  if apteka<>1 then
  form1.Label16.caption:=inttostr(apteka)+' bitar' else
  form1.Label16.caption:=inttostr(apteka)+' stycke';
  if cinema<>1 then
  form1.Label17.caption:=inttostr(cinema)+' bitar' else
  form1.Label17.caption:=inttostr(cinema)+' stycke';
  if cinemastudio<>1 then
  form1.Label18.caption:=inttostr(cinemastudio)+' bitar' else
  form1.Label18.caption:=inttostr(cinemastudio)+' stycke';
  if hostel<>1 then
  form1.Label19.caption:=inttostr(hostel)+' bitar' else
  form1.Label19.caption:=inttostr(hostel)+' stycke';
  if hotel<>1 then
  form1.Label20.caption:=inttostr(hotel)+' bitar' else
  form1.Label20.caption:=inttostr(hotel)+' stycke';
  if TC<>1 then
  form1.Label21.caption:=inttostr(TC)+' bitar' else
  form1.Label21.caption:=inttostr(TC)+' stycke';
  if autoservice<>1 then
  form1.Label22.caption:=inttostr(autoservice)+' bitar' else
  form1.Label22.caption:=inttostr(autoservice)+' stycke';
  if fitness<>1 then
  form1.Label23.caption:=inttostr(fitness)+' bitar' else
  form1.Label23.caption:=inttostr(fitness)+' stycke';
  if beauty<>1 then
  form1.Label24.caption:=inttostr(beauty)+' bitar' else
  form1.Label24.caption:=inttostr(beauty)+' stycke';
  if stomatologia<>1 then
  form1.Label25.caption:=inttostr(stomatologia)+' bitar' else
  form1.Label25.caption:=inttostr(stomatologia)+' stycke';
  if socnet<>1 then
  form1.Label26.caption:=inttostr(socnet)+' bitar' else
  form1.Label26.caption:=inttostr(socnet)+' stycke';
  if bank<>1 then
  form1.Label27.caption:=inttostr(bank)+' bitar' else
  form1.Label27.caption:=inttostr(bank)+' stycke';
  if blackgold<>1 then
  form1.Label28.caption:=inttostr(blackgold)+' bitar' else
  form1.Label28.caption:=inttostr(blackgold)+' stycke';
  if va<>1 then
  form1.Label29.caption:=inttostr(va)+' bitar' else
  form1.Label29.caption:=inttostr(va)+' stycke';
  form1.Label66.caption:='Din nivå av activa vinst';
  form1.Label65.caption:='Din nivå av passiva vinst';
  form1.Label2.caption:='Din nivå av XP';
  form1.statictext1.caption:='Affärsmän simulator';
  form1.statictext8.caption:='Liten kiosk';
  form1.statictext9.caption:='Hushållsvaror';
  form1.statictext10.caption:='Gastronom';
  form1.statictext19.caption:='Restaurang';
  form1.statictext11.caption:='Apotek';
  form1.statictext12.caption:='Bio';
  form1.statictext24.caption:='Game utveckling';
  form1.statictext13.caption:='Hostel';
  form1.statictext14.caption:='Hotell';
  form1.statictext15.caption:='Köpcentrum';
  form1.statictext17.caption:='Biltvätt';
  form1.statictext16.caption:='Fitnesscenter';
  form1.statictext18.caption:='Skönhetssalong';
  form1.statictext20.caption:='Stomatologi';
  form1.statictext23.caption:='Socialt nätwerk';
  form1.statictext21.caption:='Bank';
  form1.statictext22.caption:='Oljebolaget';
  form1.statictext25.caption:='Din aktivitet';
  form1.statictext43.caption:='Din värde';
  form1.button2.caption:='Spara';
  form1.button3.caption:='Ladda';
  form1.button4.caption:='Sluta';
  form1.button5.caption:='Författare';
  form1.button1.caption:='Hjälp';
  form1.button7.caption:='Statistik';
  form1.button9.caption:='Donera';
  form1.button10.caption:='Resultat';
  form1.button11.caption:='BugRapportera';
  form1.button31.caption:='Alternativ';
  form1.button13.caption:='köpa';
  form1.button14.caption:='köpa';
  form1.button15.caption:='köpa';
  form1.button16.caption:='köpa';
  form1.button17.caption:='köpa';
  form1.button18.caption:='köpa';
  form1.button19.caption:='köpa';
  form1.button20.caption:='köpa';
  form1.button21.caption:='köpa';
  form1.button22.caption:='köpa';
  form1.button23.caption:='köpa';
  form1.button24.caption:='köpa';
  form1.button25.caption:='köpa';
  form1.button26.caption:='köpa';
  form1.button27.caption:='köpa';
  form1.button28.caption:='köpa';
  form1.button29.caption:='köpa';
  form1.button30.caption:='köpa';
  form1.button8.caption:='Lotteri';
  form1.button6.caption:='Arbete';
  form1.radiobutton1.caption:='Rubel';
  form1.radiobutton2.caption:='Dollar';
  form1.radiobutton3.caption:='Euro';
  form1.radiobutton4.caption:='Yuan';
  form1.radiobutton5.caption:='Pounds';
  form2.button1.caption:='Tillbaka';
  form2.tabsheet1.caption:='Passiva vinst';
  form2.tabsheet2.caption:='Activa vinst';
  form2.tabsheet3.caption:='Pengar fick';
  form2.tabsheet4.caption:='Liten kiosk';
  form2.tabsheet5.caption:='Hushållsvaror';
  form2.tabsheet6.caption:='Gastronom';
  form2.tabsheet7.caption:='Restaurang';
  form2.tabsheet8.caption:='Apotek';
  form2.tabsheet9.caption:='Bio';
  form2.tabsheet10.caption:='Game utveckling';
  form2.tabsheet11.caption:='Hostel';
  form2.tabsheet12.caption:='Hotell';
  form2.tabsheet13.caption:='Köpcentrum';
  form2.tabsheet14.caption:='Biltvätt';
  form2.tabsheet15.caption:='Fitnesscenter';
  form2.tabsheet16.caption:='Skönhetssalong';
  form2.tabsheet17.caption:='Stomatologi';
  form2.tabsheet18.caption:='Socialt nätwerk';
  form2.tabsheet19.caption:='Bank';
  form2.tabsheet20.caption:='Oljebolaget';
  form2.tabsheet21.caption:='Din aktivitet';
  form2.tabsheet24.caption:='All verksamhet';
  form2.tabsheet23.caption:='Andra';
  form3.statictext1.caption:='Vill du spelet? Vill du lämna ett meddelande på webbplatsen?';
  form3.button1.caption:='Ja';
  form3.button2.caption:='Inte påminna';
  form3.button3.caption:='Inte nu';
  form4.button1.caption:='Stäng i 15 sekunder';
  form5.button1.caption:='Använda';
  form5.label1.caption:='Sätt i den hemliga nyckel';
  form6.label1.caption:='Vilka webbläsare använder du?';
  form6.button4.caption:='Andra';
  form7.groupbox2.caption:='Bakgrund';
  form7.radiobutton9.caption:='Utan bakgrund';
  form7.button1.caption:='Tillbaka till spel';
  form1.caption:='Affärsmän simulator';
  form2.caption:='Resultat';
  form3.caption:='Affärsmän simulator';
  form4.caption:='Annonser';
  form7.caption:='Alternativ';
  language:='svenska';
  check:=0
end;

procedure TForm7.RadioButton1Click(Sender: TObject);
begin
  form1.Image1.Visible:=true;
  form1.Image2.Visible:=false;
  form1.Image3.visible:=false;
  form1.image4.visible:=false;
  form1.image5.visible:=false;
  form1.image6.visible:=false;
  form1.image7.visible:=false;
  form1.image8.visible:=false;
  form2.Image1.Visible:=true;
  form2.Image356.Visible:=false;
  form2.Image357.visible:=false;
  form2.image362.visible:=false;
  form2.image358.visible:=false;
  form2.image359.visible:=false;
  form2.image360.visible:=false;
  form2.image361.visible:=false;
end;

procedure TForm7.RadioButton2Click(Sender: TObject);
begin
  form1.Image1.Visible:=false;
  form1.Image2.Visible:=true;
  form1.Image3.visible:=false;
  form1.image4.visible:=false;
  form1.image5.visible:=false;
  form1.image6.visible:=false;
  form1.image7.visible:=false;
  form1.image8.visible:=false;
  form2.Image1.Visible:=false;
  form2.Image356.Visible:=true;
  form2.Image357.visible:=false;
  form2.image362.visible:=false;
  form2.image358.visible:=false;
  form2.image359.visible:=false;
  form2.image360.visible:=false;
  form2.image361.visible:=false;
end;

procedure TForm7.RadioButton3Click(Sender: TObject);
begin
  form1.Image1.Visible:=false;
  form1.Image2.Visible:=false;
  form1.Image3.visible:=true;
  form1.image4.visible:=false;
  form1.image5.visible:=false;
  form1.image6.visible:=false;
  form1.image7.visible:=false;
  form1.image8.visible:=false;
  form2.Image1.Visible:=false;
  form2.Image356.Visible:=false;
  form2.Image357.visible:=true;
  form2.image362.visible:=false;
  form2.image358.visible:=false;
  form2.image359.visible:=false;
  form2.image360.visible:=false;
  form2.image361.visible:=false;
end;

procedure TForm7.RadioButton4Click(Sender: TObject);
begin
  form1.Image1.Visible:=false;
  form1.Image2.Visible:=false;
  form1.Image3.visible:=false;
  form1.image4.visible:=true;
  form1.image5.visible:=false;
  form1.image6.visible:=false;
  form1.image7.visible:=false;
  form1.image8.visible:=false;
  form2.Image1.Visible:=false;
  form2.Image356.Visible:=false;
  form2.Image357.visible:=false;
  form2.image362.visible:=true;
  form2.image358.visible:=false;
  form2.image359.visible:=false;
  form2.image360.visible:=false;
  form2.image361.visible:=false;
end;

procedure TForm7.RadioButton5Click(Sender: TObject);
begin
  form1.Image1.Visible:=false;
  form1.Image2.Visible:=false;
  form1.Image3.visible:=false;
  form1.image4.visible:=false;
  form1.image5.visible:=true;
  form1.image6.visible:=false;
  form1.image7.visible:=false;
  form1.image8.visible:=false;
  form2.Image1.Visible:=false;
  form2.Image356.Visible:=false;
  form2.Image357.visible:=false;
  form2.image362.visible:=false;
  form2.image358.visible:=true;
  form2.image359.visible:=false;
  form2.image360.visible:=false;
  form2.image361.visible:=false;
end;

procedure TForm7.RadioButton6Click(Sender: TObject);
begin
  form1.Image1.Visible:=false;
  form1.Image2.Visible:=false;
  form1.Image3.visible:=false;
  form1.image4.visible:=false;
  form1.image5.visible:=false;
  form1.image6.visible:=true;
  form1.image7.visible:=false;
  form1.image8.visible:=false;
  form2.Image1.Visible:=false;
  form2.Image356.Visible:=false;
  form2.Image357.visible:=false;
  form2.image362.visible:=false;
  form2.image358.visible:=false;
  form2.image359.visible:=true;
  form2.image360.visible:=false;
  form2.image361.visible:=false;
end;

procedure TForm7.RadioButton7Click(Sender: TObject);
begin
  form1.Image1.Visible:=false;
  form1.Image2.Visible:=false;
  form1.Image3.visible:=false;
  form1.image4.visible:=false;
  form1.image5.visible:=false;
  form1.image6.visible:=false;
  form1.image7.visible:=true;
  form1.image8.visible:=false;
  form2.Image1.Visible:=false;
  form2.Image356.Visible:=false;
  form2.Image357.visible:=false;
  form2.image362.visible:=false;
  form2.image358.visible:=false;
  form2.image359.visible:=false;
  form2.image360.visible:=true;
  form2.image361.visible:=false;
end;

procedure TForm7.RadioButton8Click(Sender: TObject);
begin
  form1.Image1.Visible:=false;
  form1.Image2.Visible:=false;
  form1.Image3.visible:=false;
  form1.image4.visible:=false;
  form1.image5.visible:=false;
  form1.image6.visible:=false;
  form1.image7.visible:=false;
  form1.image8.visible:=true;
  form2.Image1.Visible:=false;
  form2.Image356.Visible:=false;
  form2.Image357.visible:=false;
  form2.image362.visible:=false;
  form2.image358.visible:=false;
  form2.image359.visible:=false;
  form2.image360.visible:=false;
  form2.image361.visible:=true;
end;

procedure TForm7.RadioButton9Click(Sender: TObject);
begin
  form1.Image1.Visible:=false;
  form1.Image2.Visible:=false;
  form1.Image3.visible:=false;
  form1.image4.visible:=false;
  form1.image5.visible:=false;
  form1.image6.visible:=false;
  form1.image7.visible:=false;
  form1.image8.visible:=false;
  form2.Image1.Visible:=false;
  form2.Image356.Visible:=false;
  form2.Image357.visible:=false;
  form2.image362.visible:=false;
  form2.image358.visible:=false;
  form2.image359.visible:=false;
  form2.image360.visible:=false;
  form2.image361.visible:=false;
end;

end.

